export type Brand = 'hanzo' | 'zoo' | 'zen' | 'lux' | 'pars'

export interface BrandConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export const brandConfigs: Record<Brand, BrandConfig> = {
  hanzo: {
    name: 'Hanzo AI',
    fullName: 'Hanzo AI Inc (Techstars \'17)',
    description: 'AI compute infrastructure and market mechanisms for decentralized AI workloads',
    website: 'https://hanzo.ai',
    github: 'https://github.com/hanzoai',
    primaryColor: '#FF6B35',
    secondaryColor: '#004E89',
    accentColor: '#00D9FF',
    logo: '/logos/hanzo-logo.svg',
    papers: [
      {
        id: 'aso',
        title: 'Active Semantic Optimization (ASO)',
        subtitle: 'Training-Free GRPO for Single-Agent Adaptation',
        abstract: 'Training-free adaptation via Bayesian product-of-experts (PoE) decoding with token/embedding-level experiential priors. Foundation for Zoo\'s DSO multi-agent coordination. Achieves 99.8% cost reduction ($18 vs $10,000+).',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-aso.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-aso.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-06-15',
        authors: ['Hanzo AI Research'],
        tags: ['ASO', 'GRPO', 'Code Generation', 'Cost Reduction'],
        relatedLinks: [
          { label: 'HIP-002 Specification', url: 'https://github.com/hanzoai/papers/blob/main/hips/HIP-002-aso.md' },
          { label: 'Zoo DSO (builds on ASO)', url: 'https://github.com/zooai/papers' },
        ],
      },
      {
        id: 'dso',
        title: 'Decentralized Semantic Optimization (DSO)',
        subtitle: 'Byzantine-Robust Prior Aggregation',
        abstract: 'Decentralized learning protocol with Byzantine fault tolerance and three-layer semantic storage architecture for multi-agent coordination.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-dso.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-dso.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-07-01',
        authors: ['Hanzo AI Research'],
        tags: ['DSO', 'Byzantine Robust', 'Decentralized Learning'],
      },
      {
        id: 'hmm',
        title: 'Hamiltonian Market Maker (HMM)',
        subtitle: 'Oracle-Minimal Pricing for AI Compute Marketplace',
        abstract: 'A novel AMM design for heterogeneous compute resources with provably-stable pricing via Hamiltonian invariants. Enables oracle-minimal economic settlement for AI inference and training workloads.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-hmm.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-hmm.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-10-28',
        authors: ['Hanzo AI Research'],
        tags: ['Economics', 'DeFi', 'Compute Marketplace', 'AMM'],
        relatedLinks: [
          { label: 'HIP-004 Specification', url: 'https://github.com/hanzoai/papers/blob/main/hips/HIP-004-hmm.md' },
          { label: 'Hanzo Network', url: 'https://hanzo.ai' },
        ],
      },
      {
        id: 'network-whitepaper',
        title: 'Hanzo Network Whitepaper',
        subtitle: 'L1 Blockchain for Decentralized AI Compute',
        abstract: 'Comprehensive whitepaper describing Hanzo Network\'s Layer-1 blockchain infrastructure, integrating HMM for compute pricing and supporting PoAI consensus for quality verification.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-network-whitepaper.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-network-whitepaper.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-10-20',
        authors: ['Hanzo AI Team'],
        tags: ['Blockchain', 'Infrastructure', 'Network', 'Architecture'],
      },
      {
        id: 'network-architecture',
        title: 'Hanzo Network Architecture',
        subtitle: 'Decentralized AI Compute with Post-Quantum Security',
        abstract: 'Network architecture with post-quantum cryptography and physics-inspired LLM routing for decentralized AI compute.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-network-architecture.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-network-architecture.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-10-25',
        authors: ['Hanzo AI Team'],
        tags: ['Architecture', 'Post-Quantum', 'LLM Routing'],
      },
      {
        id: 'jin-architecture',
        title: 'Jin: Unified Multimodal AI Architecture',
        subtitle: 'Vision-Language, Audio, and Cross-Modal Understanding',
        abstract: 'Unified architecture for vision-language, audio, and cross-modal understanding in a single multimodal framework.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-jin-architecture.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-jin-architecture.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-09-01',
        authors: ['Hanzo AI Research'],
        tags: ['Multimodal', 'Vision-Language', 'Audio', 'Architecture'],
      },
      {
        id: 'jin',
        title: 'Jin: Unified Multimodal Architecture (Extended)',
        subtitle: 'Extended Technical Report',
        abstract: 'Extended technical report on the Jin multimodal AI architecture covering implementation details and benchmarks.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-jin.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-jin.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-09-15',
        authors: ['Hanzo AI Research'],
        tags: ['Multimodal', 'Architecture', 'Technical Report'],
      },
      {
        id: 'mcp-server',
        title: 'Model Context Protocol Server Architecture',
        subtitle: 'Context Management and Tool Execution for AI Systems',
        abstract: 'Context management and tool execution for AI systems via the Model Context Protocol with 260+ integrated tools.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-mcp-server.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-mcp-server.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-11-01',
        authors: ['Hanzo AI Research'],
        tags: ['MCP', 'Context Management', 'Tool Use'],
      },
      {
        id: 'agent-sdk',
        title: 'Hanzo Agent SDK',
        subtitle: 'Orchestration, Tool Use, and Memory Systems',
        abstract: 'Building AI agents with multi-agent coordination, tool use, planning, and persistent memory systems.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-agent-sdk.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-agent-sdk.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-11-15',
        authors: ['Hanzo AI Research'],
        tags: ['Agents', 'SDK', 'Tool Use', 'Memory'],
      },
      {
        id: 'ml-framework',
        title: 'Hanzo ML: Production ML Framework',
        subtitle: 'Model Serving and A/B Testing',
        abstract: 'Enterprise ML operations with model versioning, feature stores, and inference infrastructure for production deployment.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-ml-framework.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-ml-framework.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-08-01',
        authors: ['Hanzo AI Research'],
        tags: ['MLOps', 'Model Serving', 'A/B Testing'],
      },
      {
        id: 'identity-nft',
        title: 'Identity NFTs for AI Agents',
        subtitle: 'Capability Tokens for Autonomous Agents',
        abstract: 'Token standard for autonomous AI agents with economic agency, identity, and capability delegation.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-identity-nft.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-identity-nft.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-08-15',
        authors: ['Hanzo AI Research'],
        tags: ['NFT', 'AI Identity', 'Capability Tokens'],
      },
      {
        id: 'api-gateway',
        title: 'Hanzo API Gateway',
        subtitle: 'Unified Commerce API Architecture',
        abstract: 'API gateway architecture for unified commerce operations and integrations with 100+ provider support.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-api-gateway.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-api-gateway.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-05-01',
        authors: ['Hanzo AI Team'],
        tags: ['API', 'Gateway', 'Commerce'],
      },
      {
        id: 'ai-commerce',
        title: 'Hanzo: An AI-First Commerce Platform',
        subtitle: 'AI-Native Commerce Architecture',
        abstract: 'AI-native commerce platform architecture and capabilities for next-generation e-commerce.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-ai-commerce.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-ai-commerce.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-04-01',
        authors: ['Hanzo AI Team'],
        tags: ['Commerce', 'AI Platform', 'E-Commerce'],
      },
      {
        id: 'analytics-ml',
        title: 'Machine Learning for Commerce Analytics',
        subtitle: 'Predictive Models for Customer Behavior',
        abstract: 'Predictive models for customer behavior using machine learning applied to commerce analytics.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-analytics-ml.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-analytics-ml.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-04-15',
        authors: ['Hanzo AI Team'],
        tags: ['Analytics', 'ML', 'Predictions'],
      },
      {
        id: 'checkout',
        title: 'Hanzo Checkout',
        subtitle: 'Frictionless Payment Processing',
        abstract: 'Modern payment processing architecture for e-commerce with frictionless checkout flows.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-checkout.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-checkout.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-03-01',
        authors: ['Hanzo AI Team'],
        tags: ['Payments', 'Checkout', 'Commerce'],
      },
      {
        id: 'sdk-ecosystem',
        title: 'The Hanzo SDK Ecosystem',
        subtitle: 'Multi-Language Commerce Integration',
        abstract: 'TypeScript, Python, Go, and Rust SDK architecture for commerce integration.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-sdk-ecosystem.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-sdk-ecosystem.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-05-15',
        authors: ['Hanzo AI Team'],
        tags: ['SDK', 'Multi-Language', 'Integration'],
      },
      {
        id: 'webhooks',
        title: 'Event-Driven Commerce: Webhook Architecture',
        subtitle: 'Real-Time Event-Driven Integration',
        abstract: 'Real-time webhook architecture for event-driven commerce integration and automation.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-webhooks.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-webhooks.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-05-20',
        authors: ['Hanzo AI Team'],
        tags: ['Webhooks', 'Events', 'Real-Time'],
      },
      {
        id: 'astle-reactive-sdk',
        title: 'Astle.js: A Reactive JavaScript SDK',
        subtitle: 'Reactive Commerce Integration',
        abstract: 'Reactive JavaScript SDK architecture for commerce applications with observable state management.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/astle-reactive-sdk.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/astle-reactive-sdk.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-03-15',
        authors: ['Hanzo AI Team'],
        tags: ['JavaScript', 'SDK', 'Reactive'],
      },
      {
        id: 'crowdstart-commerce',
        title: 'Crowdstart: A Cloud-Native E-Commerce Platform',
        subtitle: 'Cloud-Native Commerce Architecture',
        abstract: 'Cloud-native e-commerce platform design and architecture for scalable commerce operations.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/crowdstart-commerce.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/crowdstart-commerce.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-02-01',
        authors: ['Hanzo AI Team'],
        tags: ['Cloud-Native', 'E-Commerce', 'Platform'],
      },
      {
        id: 'earle-genetic-marketing',
        title: 'Earle: Genetic Algorithms for Marketing Optimization',
        subtitle: 'Evolutionary Campaign Optimization',
        abstract: 'Evolutionary algorithms applied to marketing campaign optimization for automated A/B testing at scale.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/earle-genetic-marketing.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/earle-genetic-marketing.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-02-15',
        authors: ['Hanzo AI Team'],
        tags: ['Genetic Algorithms', 'Marketing', 'Optimization'],
      },
      {
        id: 'verus-analytics',
        title: 'Verus: Real-Time Commerce Analytics at Scale',
        subtitle: 'Streaming Analytics Infrastructure',
        abstract: 'Real-time analytics infrastructure for commerce at scale with streaming processing and dashboards.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/verus-analytics.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/verus-analytics.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2024-03-01',
        authors: ['Hanzo AI Team'],
        tags: ['Analytics', 'Real-Time', 'Scale'],
      },
      {
        id: 'llm-gateway',
        title: 'Hanzo LLM Gateway',
        subtitle: 'Unified Proxy for 100+ AI Providers',
        abstract: 'Unified LLM proxy supporting 100+ providers with intelligent routing, cost optimization, and observability.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-llm-gateway.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-llm-gateway.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['LLM', 'Gateway', 'AI Providers', 'Routing'],
      },
      {
        id: 'operative',
        title: 'Hanzo Operative: Computer Use for AI',
        subtitle: 'Browser and Desktop Automation for AI Agents',
        abstract: 'Computer use framework enabling AI agents to operate browsers and desktops autonomously with vision-based interaction.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-operative.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-operative.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['Computer Use', 'Automation', 'AI Agents', 'Vision'],
      },
      {
        id: 'chat',
        title: 'Hanzo Chat: Multi-Model AI Interface',
        subtitle: '14 Zen Models with MCP Tool Integration',
        abstract: 'AI chat platform supporting 14 Zen models and 100+ third-party providers with MCP tool integration.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-chat.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-chat.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['Chat', 'Multi-Model', 'MCP', 'Interface'],
      },
      {
        id: 'search',
        title: 'Hanzo Search: AI-Powered Search Engine',
        subtitle: 'Generative Search with Real-Time UI',
        abstract: 'AI-powered search engine with generative UI, real-time results, and semantic understanding.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-search.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-search.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['Search', 'AI', 'Generative UI', 'Semantic'],
      },
      {
        id: 'flow',
        title: 'Hanzo Flow: Visual Workflow Builder',
        subtitle: 'Visual AI Pipeline Orchestration',
        abstract: 'Visual workflow builder for AI pipeline orchestration with drag-and-drop composition.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-flow.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-flow.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['Workflow', 'Visual', 'Orchestration', 'Pipeline'],
      },
      {
        id: 'platform',
        title: 'Hanzo Platform: PaaS Infrastructure',
        subtitle: 'Platform-as-a-Service for AI Workloads',
        abstract: 'Platform-as-a-Service infrastructure for deploying and managing AI workloads at scale.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-platform.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-platform.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['PaaS', 'Infrastructure', 'Deployment', 'Cloud'],
      },
      {
        id: 'candle',
        title: 'Hanzo Candle: Rust ML Framework',
        subtitle: 'High-Performance Tensor Operations in Rust',
        abstract: 'Rust-based ML framework with tensor operations, neural network layers, and GPU acceleration.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-candle.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-candle.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['Rust', 'ML Framework', 'Tensor', 'GPU'],
      },
      {
        id: 'aci',
        title: 'Hanzo ACI: AI Chain Infrastructure',
        subtitle: 'Blockchain for Decentralized AI Operations',
        abstract: 'Blockchain infrastructure for decentralized AI compute, model verification, and inference consensus.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-aci.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-aci.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Research'],
        tags: ['Blockchain', 'AI', 'Decentralized Compute', 'Consensus'],
      },
    ],
  },
  zoo: {
    name: 'Zoo Labs',
    fullName: 'Zoo Labs Foundation (501c3)',
    description: 'Democratizing AI through decentralized training and open source frontier models',
    website: 'https://zoo.ngo',
    github: 'https://github.com/zooai',
    primaryColor: '#2ECC71',
    secondaryColor: '#27AE60',
    accentColor: '#F39C12',
    logo: '/logos/zoo-logo.svg',
    papers: [
      {
        id: 'foundation-mission',
        title: 'Zoo Labs Foundation Mission',
        subtitle: 'AI-Blockchain Research for Conservation, Education, and Science',
        abstract: '501(c)(3) non-profit mission: Conservation AI, Educational AI, and Frontier AI research for the public good.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-foundation-mission.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-foundation-mission.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-01-15',
        authors: ['Zoo Labs Foundation'],
        tags: ['Foundation', 'Conservation', 'Education', 'Mission'],
      },
      {
        id: 'network-architecture',
        title: 'Zoo Network Architecture',
        subtitle: 'Decentralized AI Training and Inference Layer',
        abstract: 'L2 AI specialization layer with HLLM integration and federated learning for decentralized training and inference.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-network-architecture.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-network-architecture.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-10-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['Architecture', 'L2', 'Federated Learning'],
      },
      {
        id: 'tokenomics',
        title: 'Zoo Tokenomics',
        subtitle: '100% Airdrop Community-Owned AI Infrastructure',
        abstract: '100% airdrop tokenomics with zero VC/private sales and democratic validator participation for community-owned AI.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-tokenomics.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-tokenomics.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-10-15',
        authors: ['Zoo Labs Foundation'],
        tags: ['Tokenomics', 'Airdrop', 'DAO Governance'],
      },
      {
        id: 'gym-training-platform',
        title: 'Gym: Democratizing AI Model Training',
        subtitle: 'Open-Source Training Infrastructure',
        abstract: 'Comprehensive open-source platform supporting 100+ models and 8 training methods for democratized AI training.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/gym-training-platform.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/gym-training-platform.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-09-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['Gym', 'Training', 'Open Source'],
      },
      {
        id: 'hllm-training-free-grpo',
        title: 'HLLM: Hamiltonian LLMs with Training-Free GRPO',
        subtitle: '99.8% Cost Reduction via Semantic Optimization',
        abstract: '99.8% cost reduction ($18 vs $10,000+) and +2.7% accuracy via semantic optimization with Hamiltonian invariants.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/hllm-training-free-grpo.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/hllm-training-free-grpo.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-08-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['HLLM', 'GRPO', 'Cost Reduction', 'Optimization'],
      },
      {
        id: 'zoo-dso',
        title: 'Zoo DSO: Decentralized Semantic Optimization',
        subtitle: 'Byzantine-Robust Prior Aggregation for Collective Intelligence',
        abstract: 'A decentralized protocol for aggregating AI model priors with Byzantine fault tolerance, enabling collective intelligence at network scale.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-dso.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-dso.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-10-28',
        authors: ['Zoo Labs Foundation'],
        tags: ['DSO', 'Byzantine Robust', 'Decentralized', 'Collective Intelligence'],
        relatedLinks: [
          { label: 'ZIP-001 Specification', url: 'https://github.com/zooai/zips/blob/main/ZIP-001-dso.md' },
          { label: 'Hanzo ASO (foundation)', url: 'https://github.com/hanzoai/papers' },
        ],
      },
      {
        id: 'experience-ledger-dso',
        title: 'Experience Ledger: Decentralized Semantic Optimization for LLMs',
        subtitle: 'Three-Layer Storage with 7680-Dim Embeddings',
        abstract: 'DSO with Byzantine-robust curation, three-layer storage, and 7680-dimensional embeddings for persistent learning.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/experience-ledger-dso.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/experience-ledger-dso.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-09-15',
        authors: ['Zoo Labs Foundation'],
        tags: ['DSO', 'Experience Ledger', 'Byzantine Robust'],
      },
      {
        id: 'zoo-experience-ledger',
        title: 'Zoo Experience Ledger',
        subtitle: 'Content-Addressable Semantic Memory',
        abstract: 'Content-addressable semantic memory system for decentralized AI with persistent learning across agents.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-experience-ledger.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-experience-ledger.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-09-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Experience Ledger', 'Semantic Memory', 'Content-Addressable'],
      },
      {
        id: 'experience-ledger',
        title: 'Experience Ledgers: Learning from Human-AI Interaction',
        subtitle: 'Persistent Semantic Memory',
        abstract: 'Persistent semantic memory from human-AI interaction for continuous learning and improvement.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/experience-ledger.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/experience-ledger.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-08-15',
        authors: ['Zoo Labs Foundation'],
        tags: ['Experience Ledger', 'Human-AI', 'Semantic Memory'],
      },
      {
        id: 'zip-002-zen-reranker',
        title: 'ZIP-002: Zen-Reranker Integration',
        subtitle: 'Native 7680-Dimensional Embeddings with BitDelta',
        abstract: 'Native 7680-dimensional embeddings with BitDelta compression (31.87x ratio) for decentralized semantic optimization.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zip-002-zen-reranker.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zip-002-zen-reranker.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-11-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['ZIP-002', 'Zen-Reranker', 'Embeddings', 'BitDelta'],
      },
      {
        id: 'zoo-poai-consensus',
        title: 'Proof of AI: Consensus for Verifiable Compute',
        subtitle: 'Verifiable AI Compute Contribution',
        abstract: 'Consensus mechanism for verifying and rewarding AI compute contributions in decentralized networks.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-poai-consensus.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-poai-consensus.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-11-15',
        authors: ['Zoo Labs Foundation'],
        tags: ['PoAI', 'Consensus', 'Verifiable Compute'],
        relatedLinks: [
          { label: 'ZIP-002 Specification', url: 'https://github.com/zooai/zips/blob/main/ZIP-002-poai.md' },
        ],
      },
      {
        id: 'poai-consensus',
        title: 'Proof of AI: Consensus Mechanisms for ML Workloads',
        subtitle: 'ML-Optimized Consensus',
        abstract: 'Consensus mechanisms designed specifically for machine learning workloads and verifiable AI computation.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/poai-consensus.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/poai-consensus.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-11-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['PoAI', 'ML Consensus', 'Proof Systems'],
      },
      {
        id: 'zoo-agent-nft',
        title: 'Agent NFTs: Token Standard for Autonomous AI Agents',
        subtitle: 'AI Agent Tokenization',
        abstract: 'Token standard for AI agents with economic agency, autonomous operation, and decentralized governance.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-agent-nft.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-agent-nft.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-07-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['Agent NFT', 'Token Standard', 'AI Agents'],
      },
      {
        id: 'agent-nft',
        title: 'Agent NFTs: Tokenized AI Ownership and Governance',
        subtitle: 'Governance Framework for AI Agents',
        abstract: 'Governance and ownership framework for tokenized AI agents with economic agency.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/agent-nft.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/agent-nft.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-07-15',
        authors: ['Zoo Labs Foundation'],
        tags: ['NFT', 'AI Ownership', 'Governance'],
      },
      {
        id: 'federated-dso',
        title: 'Federated DSO: Privacy-Preserving Distributed Learning',
        subtitle: 'Privacy-Preserving LLM Learning',
        abstract: 'Privacy-preserving distributed learning using federated DSO for LLMs across decentralized networks.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/federated-dso.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/federated-dso.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-12-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['Federated', 'Privacy', 'Distributed Learning'],
      },
      {
        id: 'embedding-7680',
        title: 'High-Dimensional Embedding Spaces for Semantic Search',
        subtitle: 'The Case for 7680 Dimensions',
        abstract: 'The case for 7680-dimensional embedding spaces in semantic search for optimal retrieval quality.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/embedding-7680.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/embedding-7680.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2024-10-01',
        authors: ['Zoo Labs Foundation'],
        tags: ['Embeddings', '7680-Dim', 'Semantic Search'],
      },
      {
        id: 'conservation-ai',
        title: 'Conservation AI: Species Protection Systems',
        subtitle: 'AI for Wildlife Conservation',
        abstract: 'AI systems for wildlife conservation and species protection at scale.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-conservation-ai.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-conservation-ai.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Conservation', 'Wildlife', 'AI', 'Species Protection'],
      },
      {
        id: 'wildlife-tracking',
        title: 'Wildlife Tracking with Computer Vision',
        subtitle: 'Real-Time Animal Detection and Monitoring',
        abstract: 'Computer vision systems for real-time wildlife tracking, detection, and monitoring.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-wildlife-tracking.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-wildlife-tracking.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Wildlife', 'Tracking', 'Computer Vision', 'Monitoring'],
      },
      {
        id: 'habitat-modeling',
        title: 'AI Habitat Modeling',
        subtitle: 'Predictive Habitat Analysis and Restoration',
        abstract: 'AI-driven predictive habitat analysis and restoration planning for conservation efforts.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-habitat-modeling.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-habitat-modeling.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Habitat', 'Modeling', 'Prediction', 'Restoration'],
      },
      {
        id: 'species-classification',
        title: 'Deep Learning for Species Classification',
        subtitle: 'Multi-Modal Species Identification',
        abstract: 'Deep learning approaches for multi-modal species identification and classification.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-species-classification.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-species-classification.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Classification', 'Deep Learning', 'Species', 'Multi-Modal'],
      },
      {
        id: 'impact-bonds',
        title: 'Conservation Impact Bonds',
        subtitle: 'Tokenized Environmental Impact Finance',
        abstract: 'Tokenized environmental impact bonds for conservation finance and DeFi composability.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-impact-bonds.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-impact-bonds.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Impact Bonds', 'Conservation', 'DeFi', 'Environment'],
      },
      {
        id: 'carbon-credits',
        title: 'AI-Verified Carbon Credits',
        subtitle: 'Satellite-Validated Carbon Offset Protocol',
        abstract: 'AI-verified carbon credit protocol with satellite validation for transparent carbon offset markets.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-carbon-credits.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-carbon-credits.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Carbon Credits', 'Verification', 'Climate', 'Satellite'],
      },
      {
        id: 'dao-governance',
        title: 'Zoo DAO Governance',
        subtitle: 'Quadratic Voting and Scientific Governance',
        abstract: 'DAO governance framework with quadratic voting for scientific research coordination.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-dao-governance.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-dao-governance.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['DAO', 'Governance', 'Quadratic Voting', 'Science'],
      },
      {
        id: 'citizen-science',
        title: 'Citizen Science Platform',
        subtitle: 'Crowdsourced Data Collection for Conservation',
        abstract: 'Platform for crowdsourced scientific data collection supporting conservation research.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-citizen-science.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-citizen-science.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Citizen Science', 'Crowdsourcing', 'Data Collection'],
      },
      {
        id: 'educational-ai',
        title: 'Educational AI for Conservation',
        subtitle: 'Adaptive Learning for Environmental Education',
        abstract: 'Adaptive learning systems for environmental education and conservation awareness.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-educational-ai.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-educational-ai.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Education', 'AI', 'Conservation', 'Learning'],
      },
      {
        id: 'research-coordination',
        title: 'Decentralized Research Coordination',
        subtitle: 'Multi-Institution Scientific Collaboration',
        abstract: 'Decentralized coordination framework for multi-institution scientific collaboration.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-research-coordination.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-research-coordination.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Research', 'Coordination', 'Decentralized', 'Collaboration'],
      },
      {
        id: 'data-commons',
        title: 'Open Data Commons for Conservation',
        subtitle: 'Shared Scientific Data Infrastructure',
        abstract: 'Open data commons infrastructure for shared scientific datasets supporting conservation research.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-data-commons.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-data-commons.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Data Commons', 'Open Data', 'Infrastructure', 'Science'],
      },
      {
        id: 'mobile-inference',
        title: 'Mobile AI Inference for Field Research',
        subtitle: 'Edge AI for Wildlife Monitoring',
        abstract: 'Mobile AI inference for field research with edge deployment for wildlife monitoring.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-mobile-inference.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-mobile-inference.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Mobile', 'Inference', 'Edge AI', 'Field Research'],
      },
      {
        id: 'federated-wildlife',
        title: 'Federated Learning for Wildlife Data',
        subtitle: 'Privacy-Preserving Cross-Organization Learning',
        abstract: 'Federated learning for privacy-preserving cross-organization wildlife data analysis.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-federated-wildlife.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-federated-wildlife.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Federated Learning', 'Privacy', 'Wildlife', 'Cross-Org'],
      },
      {
        id: 'satellite-ecology',
        title: 'Satellite Ecology with Deep Learning',
        subtitle: 'Remote Sensing for Ecosystem Monitoring',
        abstract: 'Deep learning applied to satellite remote sensing for ecosystem monitoring and ecological analysis.',
        pdfUrl: 'https://github.com/zooai/papers/raw/main/pdfs/zoo-satellite-ecology.pdf',
        latexUrl: 'https://github.com/zooai/papers/blob/main/zoo-satellite-ecology.tex',
        githubUrl: 'https://github.com/zooai/papers',
        date: '2025-02-20',
        authors: ['Zoo Labs Foundation'],
        tags: ['Satellite', 'Ecology', 'Remote Sensing', 'Deep Learning'],
      },
    ],
  },
  zen: {
    name: 'Zen AI',
    fullName: 'Zen LM',
    description: 'Frontier AI models from 600M to 1T+ parameters co-developed by Hanzo AI and Zoo Labs',
    website: 'https://zenlm.ai',
    github: 'https://github.com/zenlm',
    primaryColor: '#9B59B6',
    secondaryColor: '#8E44AD',
    accentColor: '#E74C3C',
    logo: '/logos/zen-logo.svg',
    papers: [
      {
        id: 'family-overview',
        title: 'The Zen AI Model Family',
        subtitle: 'Democratizing AI Through Efficient Architecture',
        abstract: 'Technical overview of the full Zen model family and architecture whitepaper covering 600M to 1T+ parameters.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen_family_overview.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen_family_overview.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-15',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Overview', 'Architecture', 'Model Family'],
        relatedLinks: [
          { label: 'Model Hub', url: 'https://huggingface.co/zenlm' },
          { label: 'Documentation', url: 'https://zenlm.ai' },
        ],
      },
      {
        id: 'coder',
        title: 'Zen Coder: Agentic Code Generation Models',
        subtitle: '4B-1T Parameter Code Generation',
        abstract: 'Code generation models with agentic capabilities across parameter scales from 4B to 1T.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-coder_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-coder_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Coder', 'Code Generation', 'Agentic'],
      },
      {
        id: 'omni',
        title: 'Zen-Omni: Multimodal Text Model',
        subtitle: 'Multimodal Text Understanding and Generation',
        abstract: 'Multimodal text understanding and generation across modalities in a unified architecture.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-omni_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-omni_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-22',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Omni', 'Multimodal', 'Text'],
      },
      {
        id: 'next',
        title: 'Zen-Next: Flagship Model',
        subtitle: 'Next-Generation Frontier Model',
        abstract: 'Next-generation flagship model technical report covering architecture innovations and benchmark results.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-next_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-next_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-02-01',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Flagship', 'Next-Gen', 'Model'],
      },
      {
        id: 'nano',
        title: 'Zen-Nano: Mobile and IoT Intelligence',
        subtitle: 'Ultra-Efficient Models for Edge Deployment',
        abstract: 'Ultra-efficient models for mobile and IoT deployment with minimal resource requirements.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-nano_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-nano_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-25',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Nano', 'Mobile', 'IoT', 'Edge'],
      },
      {
        id: 'eco',
        title: 'Zen-Eco: Consumer Hardware Models',
        subtitle: 'Optimized for Consumer-Grade Hardware',
        abstract: 'Models optimized for consumer-grade hardware with excellent quality-to-compute ratio.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-eco_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-eco_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-25',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Eco', 'Consumer', 'Efficient'],
      },
      {
        id: 'artist',
        title: 'Zen-Artist: Text-to-Image Generation',
        subtitle: 'High-Quality Image Synthesis',
        abstract: 'Text-to-image generation model with high-quality synthesis and artistic control.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-artist_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-artist_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-28',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Artist', 'Text-to-Image', 'Generation'],
      },
      {
        id: 'artist-edit',
        title: 'Zen-Artist-Edit: Image Editing and Inpainting',
        subtitle: 'Instruction-Following Image Editing',
        abstract: 'Image editing and inpainting capabilities with instruction-following for precise modifications.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-artist-edit_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-artist-edit_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-28',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Artist', 'Image Editing', 'Inpainting'],
      },
      {
        id: 'designer-instruct',
        title: 'Zen-Designer-Instruct: Design Generation',
        subtitle: 'Instruction-Following Design Model',
        abstract: 'Instruction-following design generation model for professional design workflows.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-designer-instruct_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-designer-instruct_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-30',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Designer', 'Instruct', 'Design'],
      },
      {
        id: 'designer-thinking',
        title: 'Zen-Designer-Thinking: Visual Reasoning',
        subtitle: 'Visual Reasoning and Analysis',
        abstract: 'Visual reasoning and analysis for design tasks with chain-of-thought design understanding.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-designer-thinking_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-designer-thinking_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-01-30',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Designer', 'Visual Reasoning', 'Analysis'],
      },
      {
        id: 'scribe',
        title: 'Zen-Scribe: Speech Recognition and Transcription',
        subtitle: 'Multi-Language Speech-to-Text',
        abstract: 'Speech recognition and transcription model with multi-language support and high accuracy.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-scribe_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-scribe_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-02-01',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Scribe', 'Speech', 'Transcription'],
      },
      {
        id: 'guard',
        title: 'Zen-Guard: Multilingual Safety Moderation',
        subtitle: 'AI Safety and Content Moderation',
        abstract: 'Safety and content moderation across languages for responsible AI deployment.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-guard_whitepaper.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-guard_whitepaper.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-02-05',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Guard', 'Safety', 'Moderation', 'Multilingual'],
      },
      {
        id: 'reranker',
        title: 'Zen-Reranker: 7680-Dimensional Embeddings',
        subtitle: 'Semantic Optimization with BitDelta Compression',
        abstract: 'High-dimensional embeddings with BitDelta compression for semantic search and retrieval optimization.',
        pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-reranker.pdf',
        latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-reranker.tex',
        githubUrl: 'https://github.com/zenlm/papers',
        date: '2025-02-10',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Reranker', 'Embeddings', '7680-Dim', 'BitDelta'],
      },
      {
        id: 'agent',
        title: 'Zen-Agent: Autonomous AI Agent Model',
        subtitle: 'Planning, Reasoning, and Tool Use',
        abstract: 'Autonomous AI agent model with planning, reasoning, and tool use capabilities.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-agent.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-agent.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Agent', 'Planning', 'Tool Use', 'Autonomous'],
      },
      {
        id: '3d',
        title: 'Zen-3D: 3D Scene Generation',
        subtitle: 'Text-to-3D and Image-to-3D Synthesis',
        abstract: '3D scene generation from text and image inputs with high-fidelity synthesis.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-3d.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-3d.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['3D', 'Generation', 'Synthesis'],
      },
      {
        id: 'world',
        title: 'Zen-World: World Model',
        subtitle: 'Predictive World Simulation',
        abstract: 'Predictive world model for simulation and planning in complex environments.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-world.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-world.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['World Model', 'Simulation', 'Prediction'],
      },
      {
        id: 'foley',
        title: 'Zen-Foley: Sound Effects Generation',
        subtitle: 'AI-Powered Foley and Sound Design',
        abstract: 'AI-powered foley and sound effects generation for film, games, and media production.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-foley.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-foley.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Audio', 'Sound Effects', 'Foley'],
      },
      {
        id: 'musician',
        title: 'Zen-Musician: Music Generation',
        subtitle: 'Composition and Arrangement AI',
        abstract: 'AI music generation model for composition, arrangement, and production.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-musician.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-musician.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Music', 'Generation', 'Composition'],
      },
      {
        id: 'voyager',
        title: 'Zen-Voyager: Embodied AI Navigation',
        subtitle: 'Autonomous Exploration and Navigation',
        abstract: 'Embodied AI model for autonomous exploration and navigation in physical and virtual environments.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-voyager.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-voyager.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Embodied AI', 'Navigation', 'Exploration'],
      },
      {
        id: 'technical-paper',
        title: 'Zen Technical Architecture',
        subtitle: 'MoDE Architecture and Training Methodology',
        abstract: 'Technical architecture report covering the MoDE (Mixture of Distilled Experts) design and training methodology.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-technical-paper.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-technical-paper.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Architecture', 'MoDE', 'Technical Report'],
      },
      {
        id: 'reasoning',
        title: 'Zen-Reasoning: Chain-of-Thought Models',
        subtitle: 'Advanced Mathematical and Logical Reasoning',
        abstract: 'Chain-of-thought reasoning model for advanced mathematical and logical problem solving.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-reasoning.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-reasoning.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Reasoning', 'CoT', 'Mathematics', 'Logic'],
      },
      {
        id: 'medical',
        title: 'Zen-Medical: Clinical AI Models',
        subtitle: 'Medical Diagnosis and Clinical Decision Support',
        abstract: 'Clinical AI model for medical diagnosis and clinical decision support systems.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-medical.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-medical.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Medical', 'Clinical', 'Diagnosis', 'Healthcare'],
      },
      {
        id: 'voice-clone',
        title: 'Zen-Voice-Clone: Voice Synthesis',
        subtitle: 'Zero-Shot Voice Cloning and TTS',
        abstract: 'Zero-shot voice cloning and text-to-speech synthesis with high fidelity.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-voice-clone.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-voice-clone.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Voice', 'TTS', 'Cloning', 'Synthesis'],
      },
      {
        id: 'translator',
        title: 'Zen-Translator: Neural Machine Translation',
        subtitle: 'Multilingual Translation Across 100+ Languages',
        abstract: 'Neural machine translation model supporting 100+ languages with high quality.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-translator.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-translator.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Translation', 'NMT', 'Multilingual'],
      },
      {
        id: 'video',
        title: 'Zen-Video: Video Generation',
        subtitle: 'Text-to-Video and Video Editing',
        abstract: 'Text-to-video generation and video editing model with temporal consistency.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-video.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-video.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Video', 'Generation', 'Editing'],
      },
      {
        id: 'director',
        title: 'Zen-Director: AI Film Production',
        subtitle: 'Scene Composition and Cinematography AI',
        abstract: 'AI-powered film production model for scene composition and cinematography.',
        pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-director.pdf',
        latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-director.tex',
        githubUrl: 'https://github.com/hanzoai/papers',
        date: '2025-02-20',
        authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
        tags: ['Film', 'Director', 'Cinematography'],
      },
    ],
  },
  lux: {
    name: 'Lux',
    fullName: 'Lux Network',
    description: 'Post-quantum secure, high-performance blockchain infrastructure - Layer-0 for Hanzo (AI Compute) and Zoo (AI/ML Specialization)',
    website: 'https://lux.network',
    github: 'https://github.com/luxfi',
    primaryColor: '#3498DB',
    secondaryColor: '#2980B9',
    accentColor: '#E67E22',
    logo: '/logos/lux-logo.svg',
    papers: [
      {
        id: 'consensus',
        title: 'Lux Consensus',
        subtitle: 'Physics-Inspired Metastable Blockchain Consensus',
        abstract: 'Novel consensus mechanism using physics-inspired metastable dynamics for high-throughput finality.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-consensus.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-consensus.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-04-01',
        authors: ['Lux Partners'],
        tags: ['Consensus', 'Physics-Inspired', 'Metastable'],
      },
      {
        id: 'quantum-consensus',
        title: 'Quantum Consensus',
        subtitle: 'Post-Quantum Cryptography with Dilithium Signatures',
        abstract: 'Implementation of NIST-standardized Dilithium post-quantum signatures for validator consensus, ensuring security against quantum computer attacks.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-quantum-consensus.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quantum-consensus.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-06-01',
        authors: ['Lux Partners'],
        tags: ['Consensus', 'Post-Quantum', 'Cryptography', 'Dilithium'],
      },
      {
        id: 'quasar-consensus',
        title: 'Quasar Consensus',
        subtitle: 'Dual-Certificate Quantum-Secure Finality (BLS + Ringtail)',
        abstract: 'Novel consensus mechanism combining BLS signatures with post-quantum Ringtail signatures for quantum-safe finality with efficient verification.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-quasar-consensus.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-quasar-consensus.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-09-01',
        authors: ['Lux Partners'],
        tags: ['Consensus', 'Post-Quantum', 'BLS', 'Ringtail', 'Finality'],
      },
      {
        id: 'fpc-consensus',
        title: 'FPC Consensus',
        subtitle: 'Fast Probabilistic Consensus with Adaptive Thresholds',
        abstract: 'High-throughput probabilistic consensus protocol with adaptive security thresholds and sub-second finality for optimal performance.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-fpc-consensus.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fpc-consensus.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-12-01',
        authors: ['Lux Partners'],
        tags: ['Consensus', 'Performance', 'Probabilistic', 'Low-Latency'],
      },
      {
        id: 'achain',
        title: 'A-Chain: Attestation Chain',
        subtitle: 'TEE Attestation & AI Compute Verification',
        abstract: 'Trusted Execution Environment attestation chain supporting Intel SGX, AMD SEV-SNP, NVIDIA H100 CC, and ARM CCA for verifiable AI compute.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-achain-attestation.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-achain-attestation.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-10-01',
        authors: ['Lux Partners'],
        tags: ['TEE', 'Attestation', 'AI Compute', 'SGX', 'SEV-SNP', 'H100'],
      },
      {
        id: 'gchain',
        title: 'G-Chain: GraphQL Chain',
        subtitle: 'Universal GraphQL Query Engine with BadgerDB',
        abstract: 'High-performance query layer with GraphQL API and BadgerDB storage for efficient blockchain data access and indexing.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-gchain-graphql.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-gchain-graphql.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-08-01',
        authors: ['Lux Partners'],
        tags: ['GraphQL', 'Indexing', 'BadgerDB', 'Query Engine'],
      },
      {
        id: 'mchain',
        title: 'M-Chain: MPC Chain',
        subtitle: 'MPC Threshold Custody (CGG21, MuSig2, FROST, Ringtail)',
        abstract: 'Multi-party computation chain for threshold custody supporting multiple protocols including post-quantum Ringtail signatures.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-mchain-mpc.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-mchain-mpc.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-09-15',
        authors: ['Lux Partners'],
        tags: ['MPC', 'Threshold Signatures', 'CGG21', 'MuSig2', 'FROST'],
      },
      {
        id: 'zchain',
        title: 'Z-Chain: Zero-Knowledge Chain',
        subtitle: 'Privacy-Preserving Smart Contracts (zkEVM, FHE, TEE)',
        abstract: 'Privacy layer combining zkEVM, fully homomorphic encryption, and trusted execution environments for confidential smart contracts.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-zchain.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-zchain.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-11-01',
        authors: ['Lux Partners'],
        tags: ['Privacy', 'zkEVM', 'FHE', 'TEE', 'Smart Contracts'],
      },
      {
        id: 'bridge',
        title: 'Lux Bridge',
        subtitle: 'Cross-Chain with ZK Light Clients & IBC Integration',
        abstract: 'Trustless cross-chain bridge using zero-knowledge light clients and IBC protocol for interoperability with Cosmos and Ethereum.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-bridge.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-bridge.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-07-01',
        authors: ['Lux Partners'],
        tags: ['Bridge', 'IBC', 'Zero-Knowledge', 'Interoperability'],
      },
      {
        id: 'ntt',
        title: 'NTT Transform',
        subtitle: '85% Gas Reduction for Post-Quantum Crypto on EVM',
        abstract: 'Number Theoretic Transform optimization for post-quantum algorithms (FALCON, Dilithium, STARKs) achieving massive gas savings.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-ntt-transform.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ntt-transform.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-05-15',
        authors: ['Lux Partners'],
        tags: ['Post-Quantum', 'NTT', 'Gas Optimization', 'EVM'],
      },
      {
        id: 'ethfalcon',
        title: 'ETHFALCON',
        subtitle: 'Post-Quantum FALCON Signatures for Ethereum',
        abstract: 'Optimized implementation of FALCON post-quantum signatures for Ethereum, enabling quantum-safe transactions.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-ethfalcon-post-quantum.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-ethfalcon-post-quantum.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-07-01',
        authors: ['Lux Partners'],
        tags: ['Post-Quantum', 'FALCON', 'Ethereum', 'Signatures'],
      },
      {
        id: 'threshold-signatures',
        title: 'Universal Threshold Signatures',
        subtitle: 'Unified Framework (CMP, FROST, LSS, Doerner, Ringtail)',
        abstract: 'Comprehensive threshold signature framework supporting multiple protocols including post-quantum Ringtail.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-universal-threshold-signatures.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-universal-threshold-signatures.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-09-01',
        authors: ['Lux Partners'],
        tags: ['Threshold Signatures', 'MPC', 'Post-Quantum', 'CMP', 'FROST'],
      },
      {
        id: 'verkle',
        title: 'Verkle Trees',
        subtitle: 'Constant-Size Proofs (~150 bytes) for Stateless Clients',
        abstract: 'Implementation of Verkle trees for efficient state proofs enabling stateless client operation with minimal bandwidth.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-verkle-trees.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-verkle-trees.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-10-01',
        authors: ['Lux Partners'],
        tags: ['Verkle Trees', 'Scalability', 'Stateless', 'State Proofs'],
      },
      {
        id: 'fraud-proofs',
        title: 'Fraud Proofs',
        subtitle: 'Optimistic Rollups with Interactive Bisection Game',
        abstract: 'Optimistic rollup implementation with efficient fraud proof mechanism using interactive bisection for dispute resolution.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-fraud-proofs.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-fraud-proofs.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-11-15',
        authors: ['Lux Partners'],
        tags: ['Layer 2', 'Optimistic Rollups', 'Fraud Proofs', 'Scalability'],
      },
      {
        id: 'tee-mesh',
        title: 'TEE Computing Mesh',
        subtitle: 'Distributed TEE Network for Confidential Computing',
        abstract: 'Mesh network of trusted execution environments (SGX, SEV-SNP, TDX, CCA) for distributed confidential computing.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-tee-computing-mesh.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tee-computing-mesh.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-12-01',
        authors: ['Lux Partners'],
        tags: ['TEE', 'Confidential Computing', 'SGX', 'SEV-SNP', 'TDX'],
      },
      {
        id: 'lightspeed-dex',
        title: 'Lightspeed DEX',
        subtitle: 'HFT-Optimized DEX with 261ms Latency & FPGA Matching',
        abstract: 'Ultra-low latency decentralized exchange with FPGA-accelerated order matching achieving institutional-grade performance.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-lightspeed-dex.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-lightspeed-dex.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-05-01',
        authors: ['Lux Partners'],
        tags: ['DeFi', 'DEX', 'HFT', 'FPGA', 'Low-Latency'],
      },
      {
        id: 'credit',
        title: 'Lux Credit',
        subtitle: 'Self-Repaying Lending with 90% LTV & 11% APY',
        abstract: 'Novel lending protocol with self-repaying mechanism, high loan-to-value ratios, and attractive yields on LUX staking.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-credit-lending.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-credit-lending.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-08-15',
        authors: ['Lux Partners'],
        tags: ['DeFi', 'Lending', 'Credit', 'Self-Repaying'],
      },
      {
        id: 'oracle',
        title: 'Oracle Infrastructure',
        subtitle: 'AI Oracle (LP-106) + Traditional Price Feeds',
        abstract: 'Hybrid oracle system combining AI-powered LP-106 protocol with Chainlink and Pyth for reliable price feeds.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-oracle-infrastructure.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-oracle-infrastructure.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-09-01',
        authors: ['Lux Partners'],
        tags: ['Oracle', 'AI', 'Price Feeds', 'Chainlink', 'Pyth'],
      },
      {
        id: 'perpetuals',
        title: 'Perpetuals & Derivatives',
        subtitle: 'GMX2 Integration with Funding Rates & Liquidation Engine',
        abstract: 'Perpetual futures and derivatives platform integrated with GMX v2 architecture for advanced trading capabilities.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-perpetuals-derivatives.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-perpetuals-derivatives.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-10-15',
        authors: ['Lux Partners'],
        tags: ['DeFi', 'Perpetuals', 'Derivatives', 'GMX', 'Trading'],
      },
      {
        id: 'market',
        title: 'Lux.market NFT',
        subtitle: 'NFT Marketplace with Reservoir Aggregation',
        abstract: 'Multi-chain NFT marketplace aggregating liquidity from 14+ chains using Reservoir protocol for optimal pricing.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-market-nft.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-market-nft.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-07-15',
        authors: ['Lux Partners'],
        tags: ['NFT', 'Marketplace', 'Reservoir', 'Multi-Chain'],
      },
      {
        id: 'id-iam',
        title: 'Lux ID IAM',
        subtitle: 'Identity & Access Management',
        abstract: 'Enterprise-grade identity and access management supporting OAuth 2.0, OIDC, SAML, WebAuthn, and multi-factor authentication.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-id-iam.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-iam.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-06-15',
        authors: ['Lux Partners'],
        tags: ['Identity', 'IAM', 'OAuth', 'WebAuthn', 'SSO'],
      },
      {
        id: 'id-did',
        title: 'Lux ID DID Specification',
        subtitle: 'Decentralized Identifiers (did:lux:)',
        abstract: 'W3C-compliant DID specification for Lux Network enabling self-sovereign identity and verifiable credentials.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-id-did-specification.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-id-did-specification.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-06-20',
        authors: ['Lux Partners'],
        tags: ['DID', 'Identity', 'W3C', 'Verifiable Credentials'],
      },
      {
        id: 'governance',
        title: 'Governance & DAO',
        subtitle: 'Multi-Ecosystem DAO (Lux, Zoo, Hanzo)',
        abstract: 'Holographic consensus-based governance spanning Lux, Zoo, and Hanzo ecosystems for unified decision-making.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-governance-dao.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-governance-dao.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-08-01',
        authors: ['Lux Partners'],
        tags: ['Governance', 'DAO', 'Holographic Consensus', 'Multi-Ecosystem'],
      },
      {
        id: 'dao-framework',
        title: 'DAO Governance Framework',
        subtitle: 'Azorius Framework with ERC6551 NFT Governance',
        abstract: 'Advanced DAO governance using Azorius framework with ERC6551 token-bound accounts for NFT-based voting.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-dao-governance-framework.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-dao-governance-framework.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2024-08-15',
        authors: ['Lux Partners'],
        tags: ['DAO', 'Governance', 'Azorius', 'ERC6551', 'NFT'],
      },
      {
        id: 'data-availability',
        title: 'Data Availability Layer',
        subtitle: 'Erasure Coding and KZG Commitments',
        abstract: 'Data availability layer using erasure coding and KZG commitments for scalable blockchain data guarantees.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-data-availability.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-data-availability.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Data Availability', 'Erasure Coding', 'KZG', 'Scalability'],
      },
      {
        id: 'economics',
        title: 'Lux Network Economics',
        subtitle: 'Appchain Economic Models and Fee Structures',
        abstract: 'Economic models and fee structures for Lux Network appchains and the broader ecosystem.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-economics.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-economics.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Economics', 'Appchain', 'Fee Structure', 'Tokenomics'],
      },
      {
        id: 'evm-precompiles',
        title: 'EVM Precompiles for Post-Quantum Cryptography',
        subtitle: 'Native Post-Quantum Operations in EVM',
        abstract: 'EVM precompiles enabling native post-quantum cryptographic operations for efficient on-chain verification.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-evm-precompiles.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-evm-precompiles.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['EVM', 'Precompiles', 'Post-Quantum', 'Cryptography'],
      },
      {
        id: 'interchain-transfers',
        title: 'Interchain Transfer Protocol',
        subtitle: 'Cross-Chain Asset Transfers with Atomic Guarantees',
        abstract: 'Cross-chain asset transfer protocol with atomic guarantees for secure interchain operations.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-interchain-transfers.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-interchain-transfers.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Interchain', 'Cross-Chain', 'Atomic', 'Transfers'],
      },
      {
        id: 'liquid-staking',
        title: 'Liquid Staking Protocol',
        subtitle: 'Staked LUX Derivatives with DeFi Composability',
        abstract: 'Liquid staking protocol for LUX with DeFi-composable staked derivatives.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-liquid-staking.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-liquid-staking.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Liquid Staking', 'DeFi', 'Staking', 'Derivatives'],
      },
      {
        id: 'privacy-pool',
        title: 'Privacy Pool Protocol',
        subtitle: 'Compliant Privacy with Selective Disclosure',
        abstract: 'Privacy pool protocol combining compliant privacy with selective disclosure using zero-knowledge proofs.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-privacy-pool.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-privacy-pool.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Privacy', 'ZK Proofs', 'Compliance', 'Selective Disclosure'],
      },
      {
        id: 'restaking',
        title: 'Restaking Protocol',
        subtitle: 'Shared Security via Validator Restaking',
        abstract: 'Restaking protocol enabling shared security through validator restaking across multiple networks.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-restaking.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-restaking.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Restaking', 'Shared Security', 'Validators', 'EigenLayer'],
      },
      {
        id: 'state-sync',
        title: 'State Synchronization Protocol',
        subtitle: 'Fast State Sync with Merkle Range Proofs',
        abstract: 'Fast state synchronization protocol using Merkle range proofs for efficient node bootstrapping.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-state-sync.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-state-sync.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['State Sync', 'Merkle Proofs', 'Performance', 'Networking'],
      },
      {
        id: 'tokenomics',
        title: 'LUX Tokenomics',
        subtitle: 'Token Distribution, Emission, and Governance',
        abstract: 'LUX token distribution, emission schedule, and governance mechanisms for the Lux Network.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-tokenomics.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-tokenomics.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Tokenomics', 'Token Distribution', 'Emission', 'Governance'],
      },
      {
        id: 'validator-economics',
        title: 'Validator Economics',
        subtitle: 'Staking Rewards, Slashing, and Economic Security',
        abstract: 'Validator economics covering staking rewards, slashing conditions, and economic security guarantees.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-validator-economics.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-validator-economics.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Validators', 'Economics', 'Staking', 'Slashing'],
      },
      {
        id: 'warp-messaging',
        title: 'Warp Messaging Protocol',
        subtitle: 'Native Cross-Chain Messaging',
        abstract: 'Native cross-chain messaging protocol for efficient inter-subnet communication on Lux Network.',
        pdfUrl: 'https://github.com/luxfi/papers/raw/main/pdfs/lux-warp-messaging.pdf',
        latexUrl: 'https://github.com/luxfi/papers/blob/main/lux-warp-messaging.tex',
        githubUrl: 'https://github.com/luxfi/papers',
        date: '2025-02-20',
        authors: ['Lux Partners'],
        tags: ['Warp', 'Messaging', 'Cross-Chain', 'Communication'],
      },
    ],
  },
  pars: {
    name: 'Pars Network',
    fullName: 'Pars DAO',
    description: 'Censorship-resistant communication and governance infrastructure for the Persian diaspora',
    website: 'https://pars.network',
    github: 'https://github.com/parsdao',
    primaryColor: '#E8B931',
    secondaryColor: '#1B4332',
    accentColor: '#FF6B6B',
    logo: '/logos/pars-logo.svg',
    papers: [
      {
        id: 'whitepaper',
        title: 'Pars Network Whitepaper',
        subtitle: 'Censorship-Resistant Infrastructure for the Persian Diaspora',
        abstract: 'Comprehensive whitepaper describing censorship-resistant infrastructure for the Persian diaspora community.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-whitepaper.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-whitepaper.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Whitepaper', 'Infrastructure', 'Censorship Resistance'],
      },
      {
        id: 'network-whitepaper',
        title: 'Pars Network Architecture',
        subtitle: 'Dual-Layer Protocol Design',
        abstract: 'Dual-layer protocol architecture for the Pars Network with EVM L2 and session daemon integration.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-network-whitepaper.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-network-whitepaper.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Architecture', 'Protocol', 'Network Design'],
      },
      {
        id: 'dual-layer',
        title: 'Dual-Layer Architecture',
        subtitle: 'EVM L2 and Session Daemon Integration',
        abstract: 'Dual-layer architecture combining EVM L2 with session daemon for censorship-resistant operations.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-dual-layer.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-dual-layer.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Dual-Layer', 'EVM', 'L2', 'Session Daemon'],
      },
      {
        id: 'mesh-networking',
        title: 'Mesh Networking Protocol',
        subtitle: 'Peer-to-Peer Communication Under Censorship',
        abstract: 'Mesh networking protocol for peer-to-peer communication in censored environments.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-mesh-networking.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-mesh-networking.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Mesh', 'P2P', 'Networking', 'Censorship'],
      },
      {
        id: 'session-protocol',
        title: 'Session Protocol',
        subtitle: 'End-to-End Encrypted Communication Layer',
        abstract: 'End-to-end encrypted communication protocol for secure messaging in the Pars Network.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-session-protocol.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-session-protocol.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Session', 'E2E Encryption', 'Communication'],
      },
      {
        id: 'post-quantum',
        title: 'Post-Quantum Cryptography for Pars',
        subtitle: 'Quantum-Resistant Security Primitives',
        abstract: 'Post-quantum cryptographic primitives for quantum-resistant security in the Pars Network.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-post-quantum.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-post-quantum.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Post-Quantum', 'Cryptography', 'Security'],
      },
      {
        id: 'coercion-resistance',
        title: 'Coercion-Resistant Governance',
        subtitle: 'Protecting Voters from External Pressure',
        abstract: 'Governance protocol protecting voters from coercion and external pressure in adversarial environments.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-coercion-resistance.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-coercion-resistance.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Governance', 'Coercion Resistance', 'Voting'],
      },
      {
        id: 'zk-identity',
        title: 'Zero-Knowledge Identity',
        subtitle: 'Privacy-Preserving Identity Verification',
        abstract: 'Zero-knowledge identity verification for privacy-preserving authentication in the Pars Network.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-zk-identity.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-zk-identity.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['ZK', 'Identity', 'Privacy', 'Verification'],
      },
      {
        id: 'stealth-addresses',
        title: 'Stealth Address Protocol',
        subtitle: 'Unlinkable Transaction Destinations',
        abstract: 'Stealth address protocol for unlinkable transaction destinations and financial privacy.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-stealth-addresses.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-stealth-addresses.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Stealth Addresses', 'Privacy', 'Transactions'],
      },
      {
        id: 'did-standard',
        title: 'Pars DID Standard',
        subtitle: 'Decentralized Identifiers for Pars Network',
        abstract: 'Decentralized identifier standard for self-sovereign identity on the Pars Network.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-did-standard.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-did-standard.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['DID', 'Identity', 'Decentralized', 'Standard'],
      },
      {
        id: 'social-recovery',
        title: 'Social Recovery Protocol',
        subtitle: 'Guardian-Based Account Recovery',
        abstract: 'Social recovery protocol with guardian-based account recovery for secure key management.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-social-recovery.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-social-recovery.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Social Recovery', 'Guardians', 'Account Recovery'],
      },
      {
        id: 'e2e-messaging',
        title: 'End-to-End Encrypted Messaging',
        subtitle: 'Signal Protocol Adaptation for Decentralized Networks',
        abstract: 'Signal Protocol adaptation for end-to-end encrypted messaging on decentralized networks.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-e2e-messaging.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-e2e-messaging.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['E2E', 'Messaging', 'Encryption', 'Signal Protocol'],
      },
      {
        id: 'persian-nlp',
        title: 'Persian NLP Infrastructure',
        subtitle: 'Natural Language Processing for Farsi',
        abstract: 'Natural language processing infrastructure for Farsi and Persian language AI applications.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-persian-nlp.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-persian-nlp.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['NLP', 'Persian', 'Farsi', 'Language'],
      },
      {
        id: 'federated-learning',
        title: 'Federated Learning for Persian AI',
        subtitle: 'Distributed Training for Low-Resource Languages',
        abstract: 'Federated learning for distributed training of Persian AI models in low-resource language settings.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-federated-learning.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-federated-learning.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Federated Learning', 'Persian', 'Distributed Training'],
      },
      {
        id: 'distributed-inference',
        title: 'Distributed Inference Protocol',
        subtitle: 'Decentralized AI Inference for Censored Regions',
        abstract: 'Distributed inference protocol for decentralized AI inference in censored regions.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-distributed-inference.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-distributed-inference.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Inference', 'Distributed', 'Decentralized', 'AI'],
      },
      {
        id: 'diaspora-bridge',
        title: 'Diaspora Bridge Protocol',
        subtitle: 'Cross-Border Financial Infrastructure',
        abstract: 'Cross-border financial infrastructure for the Persian diaspora community.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-diaspora-bridge.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-diaspora-bridge.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Bridge', 'Cross-Border', 'Finance', 'Diaspora'],
      },
      {
        id: 'dao-governance',
        title: 'Pars DAO Governance',
        subtitle: 'Democratic Governance for Diaspora Communities',
        abstract: 'Democratic governance framework for diaspora communities with coercion-resistant voting.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-dao-governance.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-dao-governance.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['DAO', 'Governance', 'Democracy', 'Community'],
      },
      {
        id: 'veasha-tokenomics',
        title: 'Veasha Tokenomics',
        subtitle: 'Token Economics for Community-Owned Infrastructure',
        abstract: 'Token economics for community-owned infrastructure in the Pars Network.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-veasha-tokenomics.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-veasha-tokenomics.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Tokenomics', 'Veasha', 'Community', 'Economics'],
      },
      {
        id: 'cultural-archives',
        title: 'Decentralized Cultural Archives',
        subtitle: 'Permanent Storage for Persian Cultural Heritage',
        abstract: 'Decentralized permanent storage for Persian cultural heritage preservation.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-cultural-archives.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-cultural-archives.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Archives', 'Culture', 'Heritage', 'Storage'],
      },
      {
        id: 'shadow-governance',
        title: 'Shadow Governance Protocol',
        subtitle: 'Governance Under Authoritarian Regimes',
        abstract: 'Shadow governance protocol enabling democratic participation under authoritarian regimes.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-shadow-governance.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-shadow-governance.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Governance', 'Shadow', 'Censorship Resistance'],
      },
      {
        id: 'asha-reserve',
        title: 'Asha Reserve Protocol',
        subtitle: 'Stablecoin Reserve for Diaspora Economics',
        abstract: 'Stablecoin reserve protocol for diaspora economics and cross-border value transfer.',
        pdfUrl: 'https://github.com/parsdao/papers/raw/main/pdfs/pars-asha-reserve.pdf',
        latexUrl: 'https://github.com/parsdao/papers/blob/main/pars-asha-reserve.tex',
        githubUrl: 'https://github.com/parsdao/papers',
        date: '2025-02-20',
        authors: ['Pars DAO'],
        tags: ['Stablecoin', 'Reserve', 'Economics', 'Asha'],
      },
    ],
  },
}

// Get brand from environment or default to hanzo
export function getBrand(): Brand {
  const brand = process.env.NEXT_PUBLIC_BRAND?.toLowerCase()
  if (brand && brand in brandConfigs) {
    return brand as Brand
  }
  return 'hanzo'
}

export function getBrandConfig(brand?: Brand): BrandConfig {
  const b = brand || getBrand()
  return brandConfigs[b]
}
