export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Hanzo AI',
  fullName: 'Hanzo AI Inc (Techstars \'17)',
  description: 'AI compute infrastructure and market mechanisms for decentralized AI workloads',
  website: 'https://hanzo.ai',
  github: 'https://github.com/hanzoai',
  primaryColor: '#FF6B35',
  secondaryColor: '#004E89',
  accentColor: '#00D9FF',
  logo: '/logos/hanzo-logo.svg',
  papers: [
    // --- Hanzo Core Papers ---
    {
      id: 'aso',
      title: 'Active Semantic Optimization (ASO)',
      subtitle: 'Training-Free GRPO for Single-Agent Adaptation',
      abstract: 'Training-free adaptation via Bayesian product-of-experts (PoE) decoding with token/embedding-level experiential priors. Foundation for Zoo\'s DSO multi-agent coordination. Achieves 99.8% cost reduction ($18 vs $10,000+).',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-aso.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-aso.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-06-15',
      authors: ['Hanzo AI Research'],
      tags: ['ASO', 'GRPO', 'Code Generation', 'Cost Reduction'],
      relatedLinks: [
        { label: 'HIP-002 Specification', url: 'https://github.com/hanzoai/papers/blob/main/hips/HIP-002-aso.md' },
        { label: 'Zoo DSO (builds on ASO)', url: 'https://github.com/zooai/papers' },
      ],
    },
    {
      id: 'dso',
      title: 'Decentralized Semantic Optimization (DSO)',
      subtitle: 'Byzantine-Robust Prior Aggregation',
      abstract: 'Decentralized learning protocol with Byzantine fault tolerance and three-layer semantic storage architecture for multi-agent coordination.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-dso.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-dso.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-07-01',
      authors: ['Hanzo AI Research'],
      tags: ['DSO', 'Byzantine Robust', 'Decentralized Learning'],
    },
    {
      id: 'hmm',
      title: 'Hamiltonian Market Maker (HMM)',
      subtitle: 'Oracle-Minimal Pricing for AI Compute Marketplace',
      abstract: 'A novel AMM design for heterogeneous compute resources with provably-stable pricing via Hamiltonian invariants. Enables oracle-minimal economic settlement for AI inference and training workloads.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-hmm.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-hmm.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-10-28',
      authors: ['Hanzo AI Research'],
      tags: ['Economics', 'DeFi', 'Compute Marketplace', 'AMM'],
      relatedLinks: [
        { label: 'HIP-004 Specification', url: 'https://github.com/hanzoai/papers/blob/main/hips/HIP-004-hmm.md' },
        { label: 'Hanzo Network', url: 'https://hanzo.ai' },
      ],
    },
    {
      id: 'network-whitepaper',
      title: 'Hanzo Network Whitepaper',
      subtitle: 'L1 Blockchain for Decentralized AI Compute',
      abstract: 'Comprehensive whitepaper describing Hanzo Network\'s Layer-1 blockchain infrastructure, integrating HMM for compute pricing and supporting PoAI consensus for quality verification.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-network-whitepaper.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-network-whitepaper.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-10-20',
      authors: ['Hanzo AI Team'],
      tags: ['Blockchain', 'Infrastructure', 'Network', 'Architecture'],
    },
    {
      id: 'network-architecture',
      title: 'Hanzo Network Architecture',
      subtitle: 'Decentralized AI Compute with Post-Quantum Security',
      abstract: 'Network architecture with post-quantum cryptography and physics-inspired LLM routing for decentralized AI compute.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-network-architecture.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-network-architecture.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-10-25',
      authors: ['Hanzo AI Team'],
      tags: ['Architecture', 'Post-Quantum', 'LLM Routing'],
    },
    {
      id: 'jin-architecture',
      title: 'Jin: Unified Multimodal AI Architecture',
      subtitle: 'Vision-Language, Audio, and Cross-Modal Understanding',
      abstract: 'Unified architecture for vision-language, audio, and cross-modal understanding in a single multimodal framework.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-jin-architecture.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-jin-architecture.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-09-01',
      authors: ['Hanzo AI Research'],
      tags: ['Multimodal', 'Vision-Language', 'Audio', 'Architecture'],
    },
    {
      id: 'jin',
      title: 'Jin: Unified Multimodal Architecture (Extended)',
      subtitle: 'Extended Technical Report',
      abstract: 'Extended technical report on the Jin multimodal AI architecture covering implementation details and benchmarks.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-jin.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-jin.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-09-15',
      authors: ['Hanzo AI Research'],
      tags: ['Multimodal', 'Architecture', 'Technical Report'],
    },
    {
      id: 'mcp-server',
      title: 'Model Context Protocol Server Architecture',
      subtitle: 'Context Management and Tool Execution for AI Systems',
      abstract: 'Context management and tool execution for AI systems via the Model Context Protocol with 260+ integrated tools.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-mcp-server.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-mcp-server.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-11-01',
      authors: ['Hanzo AI Research'],
      tags: ['MCP', 'Context Management', 'Tool Use'],
    },
    {
      id: 'agent-sdk',
      title: 'Hanzo Agent SDK',
      subtitle: 'Orchestration, Tool Use, and Memory Systems',
      abstract: 'Building AI agents with multi-agent coordination, tool use, planning, and persistent memory systems.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-agent-sdk.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-agent-sdk.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-11-15',
      authors: ['Hanzo AI Research'],
      tags: ['Agents', 'SDK', 'Tool Use', 'Memory'],
    },
    {
      id: 'ml-framework',
      title: 'Hanzo ML: Production ML Framework',
      subtitle: 'Model Serving and A/B Testing',
      abstract: 'Enterprise ML operations with model versioning, feature stores, and inference infrastructure for production deployment.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-ml-framework.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-ml-framework.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-08-01',
      authors: ['Hanzo AI Research'],
      tags: ['MLOps', 'Model Serving', 'A/B Testing'],
    },
    {
      id: 'identity-nft',
      title: 'Identity NFTs for AI Agents',
      subtitle: 'Capability Tokens for Autonomous Agents',
      abstract: 'Token standard for autonomous AI agents with economic agency, identity, and capability delegation.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-identity-nft.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-identity-nft.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-08-15',
      authors: ['Hanzo AI Research'],
      tags: ['NFT', 'AI Identity', 'Capability Tokens'],
    },
    {
      id: 'api-gateway',
      title: 'Hanzo API Gateway',
      subtitle: 'Unified Commerce API Architecture',
      abstract: 'API gateway architecture for unified commerce operations and integrations with 100+ provider support.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-api-gateway.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-api-gateway.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-05-01',
      authors: ['Hanzo AI Team'],
      tags: ['API', 'Gateway', 'Commerce'],
    },
    {
      id: 'ai-commerce',
      title: 'Hanzo: An AI-First Commerce Platform',
      subtitle: 'AI-Native Commerce Architecture',
      abstract: 'AI-native commerce platform architecture and capabilities for next-generation e-commerce.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-ai-commerce.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-ai-commerce.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-04-01',
      authors: ['Hanzo AI Team'],
      tags: ['Commerce', 'AI Platform', 'E-Commerce'],
    },
    {
      id: 'analytics-ml',
      title: 'Machine Learning for Commerce Analytics',
      subtitle: 'Predictive Models for Customer Behavior',
      abstract: 'Predictive models for customer behavior using machine learning applied to commerce analytics.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-analytics-ml.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-analytics-ml.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-04-15',
      authors: ['Hanzo AI Team'],
      tags: ['Analytics', 'ML', 'Predictions'],
    },
    {
      id: 'checkout',
      title: 'Hanzo Checkout',
      subtitle: 'Frictionless Payment Processing',
      abstract: 'Modern payment processing architecture for e-commerce with frictionless checkout flows.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-checkout.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-checkout.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-03-01',
      authors: ['Hanzo AI Team'],
      tags: ['Payments', 'Checkout', 'Commerce'],
    },
    {
      id: 'sdk-ecosystem',
      title: 'The Hanzo SDK Ecosystem',
      subtitle: 'Multi-Language Commerce Integration',
      abstract: 'TypeScript, Python, Go, and Rust SDK architecture for commerce integration.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-sdk-ecosystem.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-sdk-ecosystem.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-05-15',
      authors: ['Hanzo AI Team'],
      tags: ['SDK', 'Multi-Language', 'Integration'],
    },
    {
      id: 'webhooks',
      title: 'Event-Driven Commerce: Webhook Architecture',
      subtitle: 'Real-Time Event-Driven Integration',
      abstract: 'Real-time webhook architecture for event-driven commerce integration and automation.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-webhooks.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-webhooks.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-05-20',
      authors: ['Hanzo AI Team'],
      tags: ['Webhooks', 'Events', 'Real-Time'],
    },
    {
      id: 'astle-reactive-sdk',
      title: 'Astle.js: A Reactive JavaScript SDK',
      subtitle: 'Reactive Commerce Integration',
      abstract: 'Reactive JavaScript SDK architecture for commerce applications with observable state management.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/astle-reactive-sdk.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/astle-reactive-sdk.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-03-15',
      authors: ['Hanzo AI Team'],
      tags: ['JavaScript', 'SDK', 'Reactive'],
    },
    {
      id: 'crowdstart-commerce',
      title: 'Crowdstart: A Cloud-Native E-Commerce Platform',
      subtitle: 'Cloud-Native Commerce Architecture',
      abstract: 'Cloud-native e-commerce platform design and architecture for scalable commerce operations.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/crowdstart-commerce.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/crowdstart-commerce.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-02-01',
      authors: ['Hanzo AI Team'],
      tags: ['Cloud-Native', 'E-Commerce', 'Platform'],
    },
    {
      id: 'earle-genetic-marketing',
      title: 'Earle: Genetic Algorithms for Marketing Optimization',
      subtitle: 'Evolutionary Campaign Optimization',
      abstract: 'Evolutionary algorithms applied to marketing campaign optimization for automated A/B testing at scale.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/earle-genetic-marketing.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/earle-genetic-marketing.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-02-15',
      authors: ['Hanzo AI Team'],
      tags: ['Genetic Algorithms', 'Marketing', 'Optimization'],
    },
    {
      id: 'verus-analytics',
      title: 'Verus: Real-Time Commerce Analytics at Scale',
      subtitle: 'Streaming Analytics Infrastructure',
      abstract: 'Real-time analytics infrastructure for commerce at scale with streaming processing and dashboards.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/verus-analytics.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/verus-analytics.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-03-01',
      authors: ['Hanzo AI Team'],
      tags: ['Analytics', 'Real-Time', 'Scale'],
    },
    {
      id: 'llm-gateway',
      title: 'Hanzo LLM Gateway',
      subtitle: 'Unified Proxy for 100+ AI Providers',
      abstract: 'Unified LLM proxy supporting 100+ providers with intelligent routing, cost optimization, and observability.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-llm-gateway.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-llm-gateway.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['LLM', 'Gateway', 'AI Providers', 'Routing'],
    },
    {
      id: 'operative',
      title: 'Hanzo Operative: Computer Use for AI',
      subtitle: 'Browser and Desktop Automation for AI Agents',
      abstract: 'Computer use framework enabling AI agents to operate browsers and desktops autonomously with vision-based interaction.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-operative.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-operative.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Computer Use', 'Automation', 'AI Agents', 'Vision'],
    },
    {
      id: 'chat',
      title: 'Hanzo Chat: Multi-Model AI Interface',
      subtitle: '14 Zen Models with MCP Tool Integration',
      abstract: 'AI chat platform supporting 14 Zen models and 100+ third-party providers with MCP tool integration.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-chat.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-chat.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Chat', 'Multi-Model', 'MCP', 'Interface'],
    },
    {
      id: 'search',
      title: 'Hanzo Search: AI-Powered Search Engine',
      subtitle: 'Generative Search with Real-Time UI',
      abstract: 'AI-powered search engine with generative UI, real-time results, and semantic understanding.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-search.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-search.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Search', 'AI', 'Generative UI', 'Semantic'],
    },
    {
      id: 'flow',
      title: 'Hanzo Flow: Visual Workflow Builder',
      subtitle: 'Visual AI Pipeline Orchestration',
      abstract: 'Visual workflow builder for AI pipeline orchestration with drag-and-drop composition.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-flow.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-flow.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Workflow', 'Visual', 'Orchestration', 'Pipeline'],
    },
    {
      id: 'platform',
      title: 'Hanzo Platform: PaaS Infrastructure',
      subtitle: 'Platform-as-a-Service for AI Workloads',
      abstract: 'Platform-as-a-Service infrastructure for deploying and managing AI workloads at scale.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-platform.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-platform.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['PaaS', 'Infrastructure', 'Deployment', 'Cloud'],
    },
    {
      id: 'candle',
      title: 'Hanzo Candle: Rust ML Framework',
      subtitle: 'High-Performance Tensor Operations in Rust',
      abstract: 'Rust-based ML framework with tensor operations, neural network layers, and GPU acceleration.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-candle.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-candle.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Rust', 'ML Framework', 'Tensor', 'GPU'],
    },
    {
      id: 'aci',
      title: 'Hanzo ACI: AI Chain Infrastructure',
      subtitle: 'Blockchain for Decentralized AI Operations',
      abstract: 'Blockchain infrastructure for decentralized AI compute, model verification, and inference consensus.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-aci.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-aci.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Blockchain', 'AI', 'Decentralized Compute', 'Consensus'],
    },

    // --- Zen Model Papers (co-developed by Hanzo AI + Zoo Labs) ---
    {
      id: 'zen-family-overview',
      title: 'The Zen AI Model Family',
      subtitle: 'Democratizing AI Through Efficient Architecture',
      abstract: 'Technical overview of the full Zen model family and architecture whitepaper covering 600M to 1T+ parameters.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen_family_overview.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen_family_overview.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-15',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Overview', 'Architecture', 'Model Family'],
      relatedLinks: [
        { label: 'Model Hub', url: 'https://huggingface.co/zenlm' },
        { label: 'Documentation', url: 'https://zenlm.ai' },
      ],
    },
    {
      id: 'zen-coder',
      title: 'Zen Coder: Agentic Code Generation Models',
      subtitle: '4B-1T Parameter Code Generation',
      abstract: 'Code generation models with agentic capabilities across parameter scales from 4B to 1T.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-coder_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-coder_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Coder', 'Code Generation', 'Agentic'],
    },
    {
      id: 'zen-omni',
      title: 'Zen-Omni: Multimodal Text Model',
      subtitle: 'Multimodal Text Understanding and Generation',
      abstract: 'Multimodal text understanding and generation across modalities in a unified architecture.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-omni_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-omni_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-22',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Omni', 'Multimodal', 'Text'],
    },
    {
      id: 'zen-next',
      title: 'Zen-Next: Flagship Model',
      subtitle: 'Next-Generation Frontier Model',
      abstract: 'Next-generation flagship model technical report covering architecture innovations and benchmark results.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-next_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-next_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-01',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Flagship', 'Next-Gen', 'Model'],
    },
    {
      id: 'zen-nano',
      title: 'Zen-Nano: Mobile and IoT Intelligence',
      subtitle: 'Ultra-Efficient Models for Edge Deployment',
      abstract: 'Ultra-efficient models for mobile and IoT deployment with minimal resource requirements.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-nano_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-nano_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-25',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Nano', 'Mobile', 'IoT', 'Edge'],
    },
    {
      id: 'zen-eco',
      title: 'Zen-Eco: Consumer Hardware Models',
      subtitle: 'Optimized for Consumer-Grade Hardware',
      abstract: 'Models optimized for consumer-grade hardware with excellent quality-to-compute ratio.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-eco_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-eco_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-25',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Eco', 'Consumer', 'Efficient'],
    },
    {
      id: 'zen-artist',
      title: 'Zen-Artist: Text-to-Image Generation',
      subtitle: 'High-Quality Image Synthesis',
      abstract: 'Text-to-image generation model with high-quality synthesis and artistic control.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-artist_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-artist_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-28',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Artist', 'Text-to-Image', 'Generation'],
    },
    {
      id: 'zen-artist-edit',
      title: 'Zen-Artist-Edit: Image Editing and Inpainting',
      subtitle: 'Instruction-Following Image Editing',
      abstract: 'Image editing and inpainting capabilities with instruction-following for precise modifications.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-artist-edit_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-artist-edit_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-28',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Artist', 'Image Editing', 'Inpainting'],
    },
    {
      id: 'zen-designer-instruct',
      title: 'Zen-Designer-Instruct: Design Generation',
      subtitle: 'Instruction-Following Design Model',
      abstract: 'Instruction-following design generation model for professional design workflows.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-designer-instruct_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-designer-instruct_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-30',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Designer', 'Instruct', 'Design'],
    },
    {
      id: 'zen-designer-thinking',
      title: 'Zen-Designer-Thinking: Visual Reasoning',
      subtitle: 'Visual Reasoning and Analysis',
      abstract: 'Visual reasoning and analysis for design tasks with chain-of-thought design understanding.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-designer-thinking_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-designer-thinking_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-30',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Designer', 'Visual Reasoning', 'Analysis'],
    },
    {
      id: 'zen-scribe',
      title: 'Zen-Scribe: Speech Recognition and Transcription',
      subtitle: 'Multi-Language Speech-to-Text',
      abstract: 'Speech recognition and transcription model with multi-language support and high accuracy.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-scribe_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-scribe_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-01',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Scribe', 'Speech', 'Transcription'],
    },
    {
      id: 'zen-guard',
      title: 'Zen-Guard: Multilingual Safety Moderation',
      subtitle: 'AI Safety and Content Moderation',
      abstract: 'Safety and content moderation across languages for responsible AI deployment.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-guard_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-guard_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-05',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Guard', 'Safety', 'Moderation', 'Multilingual'],
    },
    {
      id: 'zen-reranker',
      title: 'Zen-Reranker: 7680-Dimensional Embeddings',
      subtitle: 'Semantic Optimization with BitDelta Compression',
      abstract: 'High-dimensional embeddings with BitDelta compression for semantic search and retrieval optimization.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-reranker.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-reranker.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-10',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Reranker', 'Embeddings', '7680-Dim', 'BitDelta'],
    },
    {
      id: 'zen-agent',
      title: 'Zen-Agent: Autonomous AI Agent Model',
      subtitle: 'Planning, Reasoning, and Tool Use',
      abstract: 'Autonomous AI agent model with planning, reasoning, and tool use capabilities.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-agent.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-agent.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Agent', 'Planning', 'Tool Use', 'Autonomous'],
    },
    {
      id: 'zen-3d',
      title: 'Zen-3D: 3D Scene Generation',
      subtitle: 'Text-to-3D and Image-to-3D Synthesis',
      abstract: '3D scene generation from text and image inputs with high-fidelity synthesis.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-3d.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-3d.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', '3D', 'Generation', 'Synthesis'],
    },
    {
      id: 'zen-world',
      title: 'Zen-World: World Model',
      subtitle: 'Predictive World Simulation',
      abstract: 'Predictive world model for simulation and planning in complex environments.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-world.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-world.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'World Model', 'Simulation', 'Prediction'],
    },
    {
      id: 'zen-foley',
      title: 'Zen-Foley: Sound Effects Generation',
      subtitle: 'AI-Powered Foley and Sound Design',
      abstract: 'AI-powered foley and sound effects generation for film, games, and media production.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-foley.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-foley.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Audio', 'Sound Effects', 'Foley'],
    },
    {
      id: 'zen-musician',
      title: 'Zen-Musician: Music Generation',
      subtitle: 'Composition and Arrangement AI',
      abstract: 'AI music generation model for composition, arrangement, and production.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-musician.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-musician.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Music', 'Generation', 'Composition'],
    },
    {
      id: 'zen-voyager',
      title: 'Zen-Voyager: Embodied AI Navigation',
      subtitle: 'Autonomous Exploration and Navigation',
      abstract: 'Embodied AI model for autonomous exploration and navigation in physical and virtual environments.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-voyager.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-voyager.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Embodied AI', 'Navigation', 'Exploration'],
    },
    {
      id: 'zen-technical-paper',
      title: 'Zen Technical Architecture',
      subtitle: 'MoDE Architecture and Training Methodology',
      abstract: 'Technical architecture report covering the MoDE (Mixture of Distilled Experts) design and training methodology.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-technical-paper.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-technical-paper.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Architecture', 'MoDE', 'Technical Report'],
    },
    {
      id: 'zen-reasoning',
      title: 'Zen-Reasoning: Chain-of-Thought Models',
      subtitle: 'Advanced Mathematical and Logical Reasoning',
      abstract: 'Chain-of-thought reasoning model for advanced mathematical and logical problem solving.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-reasoning.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-reasoning.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Reasoning', 'CoT', 'Mathematics', 'Logic'],
    },
    {
      id: 'zen-medical',
      title: 'Zen-Medical: Clinical AI Models',
      subtitle: 'Medical Diagnosis and Clinical Decision Support',
      abstract: 'Clinical AI model for medical diagnosis and clinical decision support systems.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-medical.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-medical.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Medical', 'Clinical', 'Diagnosis', 'Healthcare'],
    },
    {
      id: 'zen-voice-clone',
      title: 'Zen-Voice-Clone: Voice Synthesis',
      subtitle: 'Zero-Shot Voice Cloning and TTS',
      abstract: 'Zero-shot voice cloning and text-to-speech synthesis with high fidelity.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-voice-clone.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-voice-clone.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Voice', 'TTS', 'Cloning', 'Synthesis'],
    },
    {
      id: 'zen-translator',
      title: 'Zen-Translator: Neural Machine Translation',
      subtitle: 'Multilingual Translation Across 100+ Languages',
      abstract: 'Neural machine translation model supporting 100+ languages with high quality.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-translator.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-translator.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Translation', 'NMT', 'Multilingual'],
    },
    {
      id: 'zen-video',
      title: 'Zen-Video: Video Generation',
      subtitle: 'Text-to-Video and Video Editing',
      abstract: 'Text-to-video generation and video editing model with temporal consistency.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-video.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-video.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Video', 'Generation', 'Editing'],
    },
    {
      id: 'zen-director',
      title: 'Zen-Director: AI Film Production',
      subtitle: 'Scene Composition and Cinematography AI',
      abstract: 'AI-powered film production model for scene composition and cinematography.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-director.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-director.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Film', 'Director', 'Cinematography'],
    },
  ],
}
