export interface PaperConfig {
  id: string
  title: string
  subtitle: string
  abstract: string
  pdfUrl: string
  latexUrl?: string
  githubUrl: string
  date: string
  authors: string[]
  tags: string[]
  relatedLinks?: {
    label: string
    url: string
  }[]
}

export interface SiteConfig {
  name: string
  fullName: string
  description: string
  website: string
  github: string
  primaryColor: string
  secondaryColor: string
  accentColor: string
  logo: string
  papers: PaperConfig[]
}

export const siteConfig: SiteConfig = {
  name: 'Hanzo AI',
  fullName: 'Hanzo AI Inc (Techstars \'17)',
  description: 'Owned, self-hostable AI and post-quantum cryptography — sovereign infrastructure for regulated industries, critical infrastructure, and government. Technical papers, measured case studies, and formal proofs.',
  website: 'https://hanzo.ai',
  github: 'https://github.com/hanzoai',
  primaryColor: '#FF6B35',
  secondaryColor: '#004E89',
  accentColor: '#00D9FF',
  logo: '/logos/hanzo-logo.svg',
  papers: [
    // --- Sovereign AI, Security & Infrastructure ---
    {
      id: 'hanzo-security',
      title: 'Hanzo AI for Security',
      subtitle: 'Automated, Agentic Security Auditing at Estate Scale',
      abstract: 'How an agentic stack discovers and remediates security debt across sprawling microservice estates. Case study: engaged for a narrow scope, the team uncovered a 200+ microservice estate, surfaced 93 findings (22 critical) across 127+ repositories plus 780+ dependency vulnerabilities, and remediated them to zero actionable while consolidating to 3 binaries — with security built into the OSS stack via KMS, IAM, post-quantum identity, signed actions, and an immutable on-chain audit trail.',
      pdfUrl: '/pdfs/hanzo-security.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-security.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Security', 'Agentic AI', 'Audit'],
    },
    {
      id: 'hanzo-compliance',
      title: 'Hanzo AI for Compliance',
      subtitle: 'An OSS Cloud Built to Pass the Audit',
      abstract: 'The sovereign OSS stack produces audit evidence by construction — centralized IAM, KMS secrets custody, an immutable signed on-chain audit trail, post-quantum identity, and machine-checked proofs — mapping natively to SOC 2 Trust Services Criteria, NIST 800-53 control families, FINRA/SEC recordkeeping, and the defense ATO/RMF process, so compliance becomes evidence collection rather than months of manual work.',
      pdfUrl: '/pdfs/hanzo-compliance.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-compliance.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Compliance', 'SOC 2', 'ATO'],
    },
    {
      id: 'hanzo-vs-claude',
      title: 'hanzo.ai vs. claude.ai',
      subtitle: 'Owned, self-hostable AI versus a centralized cloud chat',
      abstract: 'The headline: on a regulated build where every engineer had the same model (Claude), one engineer using hanzo.ai out-shipped 30 engineers on claude.ai combined — at ~250x-900x lower cost per line. Same model; the difference was the agentic stack. Plus the deeper case for owned, self-hostable AI: data residency, air-gapped operation, post-quantum security, and cost at scale.',
      pdfUrl: '/pdfs/hanzo-vs-claude.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-vs-claude.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Post-Quantum', 'Open Weights'],
    },
    {
      id: 'hanzo-agentic-prowess',
      title: 'Agentic Engineering at Regulated Scale',
      subtitle: 'Building a Post-Quantum, FHE-Native Securities Platform',
      abstract: 'Founding CTO Zach Kelling was the #1 Anthropic user by token count worldwide in 2025 — and that throughput built a real FINRA/SEC-approved, SOC 2 securities exchange on post-quantum cryptography, a native-GPU blockchain, and fully-homomorphic encryption. The build consolidated 200+ microservices into 3 compiled binaries (3.07M → 1.06M lines) with a small team, and the FHE layer — computing on data you are not permitted to see — applies across regulated industries, from healthcare to finance to government.',
      pdfUrl: '/pdfs/hanzo-agentic-prowess.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-agentic-prowess.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Agentic AI', 'FHE', 'Post-Quantum'],
    },
    {
      id: 'hanzo-cloud-economics',
      title: 'Cloud Economics of a Sovereign OSS Stack',
      subtitle: 'A Regulated Capital-Markets Migration Case Study',
      abstract: 'Cut cloud spend ~90% — from ~$35K/mo to ~$3.5K/mo (~$380,000/yr) — migrating a regulated capital-markets platform off a sprawling public-cloud footprint (200+ microservices, 185 projects on GCP) onto a consolidated, self-hostable open-source stack on owned hardware. Decomposes where the savings come from (no metered model markup, no hyperscaler margin, efficient transport, consolidation) and shows the same mechanism applies to any organization carrying a metered-API plus hyperscaler-sprawl cost structure.',
      pdfUrl: '/pdfs/hanzo-cloud-economics.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-cloud-economics.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Cloud Economics', 'Sovereign Stack', 'OSS'],
    },
    {
      id: 'hanzo-fhe-native',
      title: 'Confidential Computing by Default',
      subtitle: 'An FHE-Native Chain and Agent Runtime',
      abstract: 'A design for making fully homomorphic encryption the default mode of computation across the two layers that normally demand plaintext: a blockchain\'s state and rules, and an autonomous agent\'s actions. State stays encrypted on-chain, policies are evaluated over ciphertext, and agents act on data they are never able to read, with a candid assessment of what is production today versus an active research frontier.',
      pdfUrl: '/pdfs/hanzo-fhe-native.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-fhe-native.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'FHE', 'Confidential Computing', 'Post-Quantum'],
    },
    {
      id: 'hanzo-zap-protocol',
      title: 'ZAP: Zero-Copy Application Protocol',
      subtitle: 'For Contested, Edge, and Bandwidth-Limited Military Environments',
      abstract: 'A high-performance binary serialization and RPC framework achieving 2.2 ns parse latency with zero allocations, 11.5M transactions per second, and 91% memory reduction versus JSON-RPC. Includes native post-quantum transport security (ML-KEM-768 + ML-DSA-65), decentralized identity via W3C DIDs, threshold agent consensus, and mesh discovery, analyzed for contested electromagnetic environments and tactical links.',
      pdfUrl: '/pdfs/hanzo-zap-protocol.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-zap-protocol.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Protocol', 'Post-Quantum', 'Edge'],
    },
    {
      id: 'hanzo-full-spectrum-cyber',
      title: 'Full-Spectrum Cryptographic Architecture',
      subtitle: 'FIPS 203/204/205 Compliant Design for Information Dominance',
      abstract: 'A cryptographic architecture implementing all three NIST post-quantum standards (ML-DSA, ML-KEM, SLH-DSA) integrated into a production blockchain consensus system with hybrid classical/quantum security and sub-second finality. Details six threshold MPC schemes over a zero-copy wire protocol, GPU-accelerated operations, an FHE virtual machine, and a key management system with Shamir secret sharing, backed by 17 formal cryptographic proofs.',
      pdfUrl: '/pdfs/hanzo-full-spectrum-cyber.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-full-spectrum-cyber.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Post-Quantum', 'FIPS', 'Cryptography'],
    },
    {
      id: 'hanzo-formal-verification',
      title: 'Machine-Checked Proofs for Post-Quantum Systems',
      subtitle: 'Automated Verification for Distributed Cryptographic Systems',
      abstract: 'A formal verification suite for a post-quantum distributed system spanning consensus, threshold cryptography, FHE, and cross-chain messaging: 50 machine-checked Lean 4 proofs, 18 cryptographic security reductions, 12 protocol-correctness proofs, and 7 DeFi invariant proofs, plus symbolic execution, fuzz targets, and NIST KAT validation. Identifies the critical gaps and presents a phased roadmap for closing them.',
      pdfUrl: '/pdfs/hanzo-formal-verification.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-formal-verification.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Formal Verification', 'Lean 4', 'Post-Quantum'],
    },
    {
      id: 'hanzo-agentic-ai',
      title: 'Agentic AI for Autonomous Cyber Operations',
      subtitle: 'Multi-Domain Intelligence Fusion and Tactical Decision Support',
      abstract: 'An agentic AI framework of 83 specialized agents and 15 orchestrators for autonomous cyber operations, intelligence fusion, and tactical decision support across a control plane, an agent SDK with native MCP integration, and a ZAP-based consensus protocol with post-quantum authentication. Agents execute 200--300 sequential tool calls and run fully disconnected on edge hardware using quantized Zen models.',
      pdfUrl: '/pdfs/hanzo-agentic-ai.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-agentic-ai.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Agentic AI', 'Cyber Operations', 'Intelligence'],
    },
    {
      id: 'hanzo-edge-ai-ml',
      title: 'Edge-Deployable AI/ML Framework',
      subtitle: 'For Disconnected Tactical Environments',
      abstract: 'An edge-deployable AI/ML framework for disconnected, degraded, and bandwidth-limited environments, combining a Rust-native inference engine for 15+ text and 16+ vision architectures with aggressive 2--8 bit quantization across hardware from laptops to embedded ARM. A family of 18 models provides capability tiers from nano-scale edge inference to frontier reasoning, operating fully offline with sandboxed execution and no cloud dependencies.',
      pdfUrl: '/pdfs/hanzo-edge-ai-ml.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-edge-ai-ml.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Edge AI', 'Quantization', 'Offline'],
    },
    {
      id: 'hanzo-cross-domain',
      title: 'Multi-Level Security and Cross-Domain Solutions',
      subtitle: 'Homomorphic Policy Evaluation and Zero-Trust Fabric',
      abstract: 'A cross-domain solution where data-transfer policies are evaluated on encrypted content using FHE so the guard never observes plaintext, integrating a zero-trust overlay with identity-first micro-segmentation, an FHE policy engine, Shamir-based key management, and org-scoped identity. Cross-domain transfers are cryptographically mediated and produce immutable audit records anchored to a post-quantum blockchain.',
      pdfUrl: '/pdfs/hanzo-cross-domain.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-cross-domain.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Cross-Domain', 'FHE', 'Zero-Trust'],
    },
    {
      id: 'hanzo-assured-networking',
      title: 'Post-Quantum Resilient Mesh Networking',
      subtitle: 'For Maritime and Tactical Edge Operations',
      abstract: 'A post-quantum resilient networking architecture for maritime, tactical edge, and DDIL environments, integrating the Reticulum Network Stack as a native consensus transport over LoRa, packet radio, serial, and mesh topologies without centralized infrastructure or DNS. All sessions use hybrid post-quantum key exchange and authentication, with a zero-trust overlay and sub-second consensus finality over mesh networks.',
      pdfUrl: '/pdfs/hanzo-assured-networking.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-assured-networking.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Mesh Networking', 'Post-Quantum', 'Maritime'],
    },
    {
      id: 'hanzo-countermeasures',
      title: 'Quantum-Resistant Counter-Exploitation',
      subtitle: 'Confidential Compute and Coercion-Resistant Communications',
      abstract: 'A suite of counter-exploitation technologies providing quantum-resistant secure messaging at 526,000 messages per second with forward secrecy, FHE with threshold decryption, post-quantum anonymous ring signatures with linkability, zero-knowledge privacy pools, and a multi-agent adversarial framework. Together these prevent adversary exploitation of cryptographic, network, and AI systems in contested environments.',
      pdfUrl: '/pdfs/hanzo-countermeasures.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-countermeasures.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Counter-Exploitation', 'Post-Quantum', 'FHE'],
    },
    {
      id: 'hanzo-quantum-sensing-qkd',
      title: 'Quantum Key Distribution and Quantum Sensing Integration',
      subtitle: 'For Post-Quantum Blockchain Consensus and Threshold Cryptography',
      abstract: 'An architecture integrating quantum key distribution hardware and quantum sensors into a production post-quantum blockchain stack. A triple-hybrid key derivation combines classical Diffie-Hellman, lattice encapsulation, and physics-layer QKD secrets so link security holds if any one of three independent foundations holds. Quantum sensors feed cryptographically attested measurements on-chain via a sensor oracle with dual threshold signatures.',
      pdfUrl: '/pdfs/hanzo-quantum-sensing-qkd.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-quantum-sensing-qkd.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'QKD', 'Quantum Sensing', 'Post-Quantum'],
    },
    {
      id: 'hanzo-test-evaluation',
      title: 'Automated Verification and Validation Framework',
      subtitle: 'With Digital Twin Environments',
      abstract: 'An integrated verification and validation framework combining continuous observability, behavioral analytics, ML pipeline orchestration, digital twin environments, and formal cryptographic proofs. Telemetry across 100+ AI providers feeds an OLAP backend, workflows orchestrate LLM evaluation, and a network simulation environment with 38 virtual machines enables mission rehearsal and system qualification with statistical decision support.',
      pdfUrl: '/pdfs/hanzo-test-evaluation.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/defense/hanzo-test-evaluation.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Sovereign AI', 'Test & Evaluation', 'Digital Twin', 'Observability'],
    },

    // --- Engine / AI Infrastructure (measured, on-device) ---
    {
      id: 'hanzo-native-stack-thesis',
      title: 'One Native Stack for Private, Continuously-Learning AI',
      subtitle: 'Inference at the Bandwidth Wall, On-Device QLoRA, One Engine',
      abstract: 'A synthesis paper: train and serve collapse into a single Rust engine with one tensor type, one quantization core, and one device backend — eliminating the format-break tax of training in PyTorch, exporting to GGUF/ONNX, and serving on a third engine. Formalizes a unified bandwidth-budget theorem and QLoRA bit-exactness, with every claim sourced to a measured ROCm campaign on consumer hardware. Scrupulously scoped: claims no speed win over NVIDIA and no zero-leakage guarantee.',
      pdfUrl: '/pdfs/hanzo-native-stack-thesis.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-native-stack-thesis.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Engine', 'Inference', 'On-Device', 'Privacy'],
    },
    {
      id: 'hanzo-rocm-inference',
      title: 'Native ROCm Inference on a Consumer RDNA3.5 APU',
      subtitle: 'Reaching llama.cpp Decode Parity via a Unified 1-bit-to-Full Quant Core',
      abstract: 'A measurement-driven engineering campaign that took native-ROCm LLM inference on a consumer AMD Ryzen AI Max+ 395 "Strix Halo" (Radeon 8060S, gfx1151) from the slowest of five backends to decode parity (0.98×) and 0.86× prefill versus llama.cpp on the same GPU. A lane-strided decode kernel reaches 245.8 GB/s — 97% of the memory-bandwidth wall. Documents negative results in detail and derives the physical ~25 tok/s ceiling that bounds both engines.',
      pdfUrl: '/pdfs/hanzo-rocm-inference.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-rocm-inference.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Engine', 'ROCm', 'Inference', 'Benchmarks'],
    },
    {
      id: 'hanzo-cross-backend-inference',
      title: 'Edge LLM Inference Across Commodity Accelerators',
      subtitle: 'Measured AMD, NVIDIA, and Apple Performance',
      abstract: 'Measured single-GPU inference for one 8B dense transformer at Q8_0 across three commodity edge accelerators — AMD "Strix Halo", NVIDIA GB10 "Grace Blackwell", and Apple M4 Max — comparing the Hanzo engine to llama.cpp on identical model and metric. Two findings: decode parity on all three backends, and the fastest box flips by workload (NVIDIA wins prefill, Apple wins decode ~2.5×). Includes a full reproducibility appendix with exact hardware, commands, and git SHA.',
      pdfUrl: '/pdfs/hanzo-cross-backend-inference.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-cross-backend-inference.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Engine', 'Inference', 'Edge', 'Benchmarks'],
    },
    {
      id: 'hanzo-native-training',
      title: 'Native Training in the Hanzo Engine',
      subtitle: 'One Engine, One Quant Format, One Backend',
      abstract: 'The architecture for training language models natively inside the Hanzo Rust inference stack, eliminating the conversion boundary between a Python training stack and a separate serving engine. Shows the QLoRA primitive already exists in the engine\'s reverse-mode autograd, and formalizes QLoRA parameter/memory accounting plus additive LoRA-soup composition. Unusually candid: an entire section names the stack\'s own non-functional stubs to replace.',
      pdfUrl: '/pdfs/hanzo-native-training.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-native-training.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Engine', 'Training', 'QLoRA', 'On-Device'],
    },
    {
      id: 'hanzo-continuous-learning-privacy',
      title: 'Continuously-Learning Private AI',
      subtitle: 'Self-Improvement and Privacy in the Hanzo Native Stack',
      abstract: 'A private continuously-learning model as three loops: an inference loop that serves and captures its own interactions, a curation loop that filters/redacts/de-duplicates into safe training data, and a training loop that folds it back into cheap swappable adapters. Formalizes a privacy invariant (no PII token enters the training set under a sound gate) and bounded-forgetting (frozen base → zero base drift), and is honest about model-collapse and delta-leakage failure modes and which components are still research.',
      pdfUrl: '/pdfs/hanzo-continuous-learning-privacy.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-continuous-learning-privacy.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Engine', 'Privacy', 'Continual Learning', 'On-Device'],
    },
    {
      id: 'hanzo-platform-infra-desktop',
      title: 'Economical Serving and the hanzo.ai Platform',
      subtitle: 'A Bandwidth-Optimal Unified Train-and-Serve Runtime',
      abstract: 'The serving economics, platform architecture, and on-device thesis that follow from a native Rust train-and-inference engine whose decode kernel runs at the memory-bandwidth wall. Derives a cost law (tokens/$/s ∝ B / (q·N_active)) showing quantization — not bigger accelerators — is the primary cost lever, and proves paged-attention tenant concurrency and a structural egress bound (raw data never crosses the wire). Honestly marks train/personalize/federate as stub/roadmap.',
      pdfUrl: '/pdfs/hanzo-platform-infra-desktop.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-platform-infra-desktop.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-06-15',
      authors: ['Zach Kelling'],
      tags: ['Engine', 'Economics', 'Platform', 'On-Device'],
    },

    {
      id: 'hanzo-unified-tenant-cloud',
      title: 'The Unified Sovereign-Tenant Cloud',
      subtitle: 'Linear Shared-Nothing Scaling via Per-Tenant SQLite and In-Process Composition',
      abstract: 'The measured memory-and-scaling case for running an entire multi-tenant cloud as one Go binary — 56 in-process subsystems over shared-nothing storage, where every tenant is its own post-quantum-encrypted SQLite file and writes shard embarrassingly with no global lock. Measured through the production open path: an actively-served tenant costs ≈0.25 MB of RAM and an idle tenant essentially zero, so memory scales with concurrency, not registrations — one billion registered tenants at 1% peak concurrency fits ≈20 commodity 128 GB nodes. Measures the shared-Postgres microservice-mesh alternative at 11–32× the memory footprint, and is explicit about writer-pinning failover, hot-tenant skew, and cross-tenant query limits.',
      pdfUrl: '/pdfs/hanzo-unified-tenant-cloud.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-unified-tenant-cloud.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2026-07-08',
      authors: ['Zach Kelling'],
      tags: ['Cloud', 'Multi-Tenancy', 'SQLite', 'Benchmarks'],
    },

    // --- Hanzo Core Papers ---
    {
      id: 'aso',
      title: 'Active Semantic Optimization (ASO)',
      subtitle: 'Training-Free GRPO for Single-Agent Adaptation',
      abstract: 'Training-free adaptation via Bayesian product-of-experts (PoE) decoding with token/embedding-level experiential priors. Foundation for Zoo\'s DSO multi-agent coordination. Achieves 99.8% cost reduction ($18 vs $10,000+).',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-aso.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-aso.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-06-15',
      authors: ['Hanzo AI Research'],
      tags: ['ASO', 'GRPO', 'Code Generation', 'Cost Reduction'],
      relatedLinks: [
        { label: 'HIP-002 Specification', url: 'https://github.com/hanzoai/papers/blob/main/hips/HIP-002-aso.md' },
        { label: 'Zoo DSO (builds on ASO)', url: 'https://github.com/zooai/papers' },
      ],
    },
    {
      id: 'dso',
      title: 'Decentralized Semantic Optimization (DSO)',
      subtitle: 'Byzantine-Robust Prior Aggregation',
      abstract: 'Decentralized learning protocol with Byzantine fault tolerance and three-layer semantic storage architecture for multi-agent coordination.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-dso.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-dso.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-07-01',
      authors: ['Hanzo AI Research'],
      tags: ['DSO', 'Byzantine Robust', 'Decentralized Learning'],
    },
    {
      id: 'hmm',
      title: 'Hamiltonian Market Maker (HMM)',
      subtitle: 'Oracle-Minimal Pricing for AI Compute Marketplace',
      abstract: 'A novel AMM design for heterogeneous compute resources with provably-stable pricing via Hamiltonian invariants. Enables oracle-minimal economic settlement for AI inference and training workloads.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-hmm.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-hmm.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-10-28',
      authors: ['Hanzo AI Research'],
      tags: ['Economics', 'DeFi', 'Compute Marketplace', 'AMM'],
      relatedLinks: [
        { label: 'HIP-004 Specification', url: 'https://github.com/hanzoai/papers/blob/main/hips/HIP-004-hmm.md' },
        { label: 'Hanzo Network', url: 'https://hanzo.ai' },
      ],
    },
    {
      id: 'network-whitepaper',
      title: 'Hanzo Network Whitepaper',
      subtitle: 'L1 Blockchain for Decentralized AI Compute',
      abstract: 'Comprehensive whitepaper describing Hanzo Network\'s Layer-1 blockchain infrastructure, integrating HMM for compute pricing and supporting PoAI consensus for quality verification.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-network-whitepaper.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-network-whitepaper.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-10-20',
      authors: ['Hanzo AI Team'],
      tags: ['Blockchain', 'Infrastructure', 'Network', 'Architecture'],
    },
    {
      id: 'network-architecture',
      title: 'Hanzo Network Architecture',
      subtitle: 'Decentralized AI Compute with Post-Quantum Security',
      abstract: 'Network architecture with post-quantum cryptography and physics-inspired LLM routing for decentralized AI compute.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-network-architecture.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-network-architecture.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-10-25',
      authors: ['Hanzo AI Team'],
      tags: ['Architecture', 'Post-Quantum', 'LLM Routing'],
    },
    {
      id: 'jin-architecture',
      title: 'Jin: Unified Multimodal AI Architecture',
      subtitle: 'Vision-Language, Audio, and Cross-Modal Understanding',
      abstract: 'Unified architecture for vision-language, audio, and cross-modal understanding in a single multimodal framework.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-jin-architecture.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-jin-architecture.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-09-01',
      authors: ['Hanzo AI Research'],
      tags: ['Multimodal', 'Vision-Language', 'Audio', 'Architecture'],
    },
    {
      id: 'jin',
      title: 'Jin: Unified Multimodal Architecture (Extended)',
      subtitle: 'Extended Technical Report',
      abstract: 'Extended technical report on the Jin multimodal AI architecture covering implementation details and benchmarks.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-jin.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-jin.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-09-15',
      authors: ['Hanzo AI Research'],
      tags: ['Multimodal', 'Architecture', 'Technical Report'],
    },
    {
      id: 'mcp-server',
      title: 'Model Context Protocol Server Architecture',
      subtitle: 'Context Management and Tool Execution for AI Systems',
      abstract: 'Context management and tool execution for AI systems via the Model Context Protocol with 260+ integrated tools.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-mcp-server.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-mcp-server.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-11-01',
      authors: ['Hanzo AI Research'],
      tags: ['MCP', 'Context Management', 'Tool Use'],
    },
    {
      id: 'agent-sdk',
      title: 'Hanzo Agent SDK',
      subtitle: 'Orchestration, Tool Use, and Memory Systems',
      abstract: 'Building AI agents with multi-agent coordination, tool use, planning, and persistent memory systems.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-agent-sdk.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-agent-sdk.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-11-15',
      authors: ['Hanzo AI Research'],
      tags: ['Agents', 'SDK', 'Tool Use', 'Memory'],
    },
    {
      id: 'ml-framework',
      title: 'Hanzo ML: Production ML Framework',
      subtitle: 'Model Serving and A/B Testing',
      abstract: 'Enterprise ML operations with model versioning, feature stores, and inference infrastructure for production deployment.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-ml-framework.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-ml-framework.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-08-01',
      authors: ['Hanzo AI Research'],
      tags: ['MLOps', 'Model Serving', 'A/B Testing'],
    },
    {
      id: 'identity-nft',
      title: 'Identity NFTs for AI Agents',
      subtitle: 'Capability Tokens for Autonomous Agents',
      abstract: 'Token standard for autonomous AI agents with economic agency, identity, and capability delegation.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-identity-nft.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-identity-nft.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-08-15',
      authors: ['Hanzo AI Research'],
      tags: ['NFT', 'AI Identity', 'Capability Tokens'],
    },
    {
      id: 'api-gateway',
      title: 'Hanzo API Gateway',
      subtitle: 'Unified Commerce API Architecture',
      abstract: 'API gateway architecture for unified commerce operations and integrations with 100+ provider support.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-api-gateway.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-api-gateway.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-05-01',
      authors: ['Hanzo AI Team'],
      tags: ['API', 'Gateway', 'Commerce'],
    },
    {
      id: 'ai-commerce',
      title: 'Hanzo: An AI-First Commerce Platform',
      subtitle: 'AI-Native Commerce Architecture',
      abstract: 'AI-native commerce platform architecture and capabilities for next-generation e-commerce.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-ai-commerce.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-ai-commerce.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-04-01',
      authors: ['Hanzo AI Team'],
      tags: ['Commerce', 'AI Platform', 'E-Commerce'],
    },
    {
      id: 'analytics-ml',
      title: 'Machine Learning for Commerce Analytics',
      subtitle: 'Predictive Models for Customer Behavior',
      abstract: 'Predictive models for customer behavior using machine learning applied to commerce analytics.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-analytics-ml.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-analytics-ml.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-04-15',
      authors: ['Hanzo AI Team'],
      tags: ['Analytics', 'ML', 'Predictions'],
    },
    {
      id: 'checkout',
      title: 'Hanzo Checkout',
      subtitle: 'Frictionless Payment Processing',
      abstract: 'Modern payment processing architecture for e-commerce with frictionless checkout flows.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-checkout.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-checkout.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-03-01',
      authors: ['Hanzo AI Team'],
      tags: ['Payments', 'Checkout', 'Commerce'],
    },
    {
      id: 'sdk-ecosystem',
      title: 'The Hanzo SDK Ecosystem',
      subtitle: 'Multi-Language Commerce Integration',
      abstract: 'TypeScript, Python, Go, and Rust SDK architecture for commerce integration.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-sdk-ecosystem.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-sdk-ecosystem.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-05-15',
      authors: ['Hanzo AI Team'],
      tags: ['SDK', 'Multi-Language', 'Integration'],
    },
    {
      id: 'webhooks',
      title: 'Event-Driven Commerce: Webhook Architecture',
      subtitle: 'Real-Time Event-Driven Integration',
      abstract: 'Real-time webhook architecture for event-driven commerce integration and automation.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-webhooks.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-webhooks.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-05-20',
      authors: ['Hanzo AI Team'],
      tags: ['Webhooks', 'Events', 'Real-Time'],
    },
    {
      id: 'astle-reactive-sdk',
      title: 'Astle.js: A Reactive JavaScript SDK',
      subtitle: 'Reactive Commerce Integration',
      abstract: 'Reactive JavaScript SDK architecture for commerce applications with observable state management.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/astle-reactive-sdk.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/astle-reactive-sdk.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-03-15',
      authors: ['Hanzo AI Team'],
      tags: ['JavaScript', 'SDK', 'Reactive'],
    },
    {
      id: 'crowdstart-commerce',
      title: 'Crowdstart: A Cloud-Native E-Commerce Platform',
      subtitle: 'Cloud-Native Commerce Architecture',
      abstract: 'Cloud-native e-commerce platform design and architecture for scalable commerce operations.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/crowdstart-commerce.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/crowdstart-commerce.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-02-01',
      authors: ['Hanzo AI Team'],
      tags: ['Cloud-Native', 'E-Commerce', 'Platform'],
    },
    {
      id: 'earle-genetic-marketing',
      title: 'Earle: Genetic Algorithms for Marketing Optimization',
      subtitle: 'Evolutionary Campaign Optimization',
      abstract: 'Evolutionary algorithms applied to marketing campaign optimization for automated A/B testing at scale.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/earle-genetic-marketing.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/earle-genetic-marketing.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-02-15',
      authors: ['Hanzo AI Team'],
      tags: ['Genetic Algorithms', 'Marketing', 'Optimization'],
    },
    {
      id: 'verus-analytics',
      title: 'Verus: Real-Time Commerce Analytics at Scale',
      subtitle: 'Streaming Analytics Infrastructure',
      abstract: 'Real-time analytics infrastructure for commerce at scale with streaming processing and dashboards.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/verus-analytics.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/verus-analytics.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2024-03-01',
      authors: ['Hanzo AI Team'],
      tags: ['Analytics', 'Real-Time', 'Scale'],
    },
    {
      id: 'llm-gateway',
      title: 'Hanzo LLM Gateway',
      subtitle: 'Unified Proxy for 100+ AI Providers',
      abstract: 'Unified LLM proxy supporting 100+ providers with intelligent routing, cost optimization, and observability.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-llm-gateway.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-llm-gateway.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['LLM', 'Gateway', 'AI Providers', 'Routing'],
    },
    {
      id: 'operative',
      title: 'Hanzo Operative: Computer Use for AI',
      subtitle: 'Browser and Desktop Automation for AI Agents',
      abstract: 'Computer use framework enabling AI agents to operate browsers and desktops autonomously with vision-based interaction.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-operative.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-operative.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Computer Use', 'Automation', 'AI Agents', 'Vision'],
    },
    {
      id: 'chat',
      title: 'Hanzo Chat: Multi-Model AI Interface',
      subtitle: '14 Zen Models with MCP Tool Integration',
      abstract: 'AI chat platform supporting 14 Zen models and 100+ third-party providers with MCP tool integration.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-chat.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-chat.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Chat', 'Multi-Model', 'MCP', 'Interface'],
    },
    {
      id: 'search',
      title: 'Hanzo Search: AI-Powered Search Engine',
      subtitle: 'Generative Search with Real-Time UI',
      abstract: 'AI-powered search engine with generative UI, real-time results, and semantic understanding.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-search.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-search.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Search', 'AI', 'Generative UI', 'Semantic'],
    },
    {
      id: 'flow',
      title: 'Hanzo Flow: Visual Workflow Builder',
      subtitle: 'Visual AI Pipeline Orchestration',
      abstract: 'Visual workflow builder for AI pipeline orchestration with drag-and-drop composition.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-flow.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-flow.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Workflow', 'Visual', 'Orchestration', 'Pipeline'],
    },
    {
      id: 'platform',
      title: 'Hanzo Platform: PaaS Infrastructure',
      subtitle: 'Platform-as-a-Service for AI Workloads',
      abstract: 'Platform-as-a-Service infrastructure for deploying and managing AI workloads at scale.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-platform.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-platform.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['PaaS', 'Infrastructure', 'Deployment', 'Cloud'],
    },
    {
      id: 'candle',
      title: 'Hanzo Candle: Rust ML Framework',
      subtitle: 'High-Performance Tensor Operations in Rust',
      abstract: 'Rust-based ML framework with tensor operations, neural network layers, and GPU acceleration.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-candle.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-candle.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Rust', 'ML Framework', 'Tensor', 'GPU'],
    },
    {
      id: 'aci',
      title: 'Hanzo ACI: AI Chain Infrastructure',
      subtitle: 'Blockchain for Decentralized AI Operations',
      abstract: 'Blockchain infrastructure for decentralized AI compute, model verification, and inference consensus.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/hanzo-aci.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/hanzo-aci.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Research'],
      tags: ['Blockchain', 'AI', 'Decentralized Compute', 'Consensus'],
    },

    // --- Zen Model Papers (co-developed by Hanzo AI + Zoo Labs) ---
    {
      id: 'zen-family-overview',
      title: 'The Zen AI Model Family',
      subtitle: 'Democratizing AI Through Efficient Architecture',
      abstract: 'Technical overview of the full Zen model family and architecture whitepaper covering 600M to 1T+ parameters.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen_family_overview.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen_family_overview.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-15',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Overview', 'Architecture', 'Model Family'],
      relatedLinks: [
        { label: 'Model Hub', url: 'https://huggingface.co/zenlm' },
        { label: 'Documentation', url: 'https://zenlm.ai' },
      ],
    },
    {
      id: 'zen-coder',
      title: 'Zen Coder: Agentic Code Generation Models',
      subtitle: '4B-1T Parameter Code Generation',
      abstract: 'Code generation models with agentic capabilities across parameter scales from 4B to 1T.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-coder_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-coder_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Coder', 'Code Generation', 'Agentic'],
    },
    {
      id: 'zen-omni',
      title: 'Zen-Omni: Multimodal Text Model',
      subtitle: 'Multimodal Text Understanding and Generation',
      abstract: 'Multimodal text understanding and generation across modalities in a unified architecture.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-omni_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-omni_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-22',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Omni', 'Multimodal', 'Text'],
    },
    {
      id: 'zen-next',
      title: 'Zen-Next: Flagship Model',
      subtitle: 'Next-Generation Frontier Model',
      abstract: 'Next-generation flagship model technical report covering architecture innovations and benchmark results.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-next_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-next_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-01',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Flagship', 'Next-Gen', 'Model'],
    },
    {
      id: 'zen-nano',
      title: 'Zen-Nano: Mobile and IoT Intelligence',
      subtitle: 'Ultra-Efficient Models for Edge Deployment',
      abstract: 'Ultra-efficient models for mobile and IoT deployment with minimal resource requirements.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-nano_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-nano_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-25',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Nano', 'Mobile', 'IoT', 'Edge'],
    },
    {
      id: 'zen-eco',
      title: 'Zen-Eco: Consumer Hardware Models',
      subtitle: 'Optimized for Consumer-Grade Hardware',
      abstract: 'Models optimized for consumer-grade hardware with excellent quality-to-compute ratio.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-eco_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-eco_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-25',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Eco', 'Consumer', 'Efficient'],
    },
    {
      id: 'zen-artist',
      title: 'Zen-Artist: Text-to-Image Generation',
      subtitle: 'High-Quality Image Synthesis',
      abstract: 'Text-to-image generation model with high-quality synthesis and artistic control.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-artist_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-artist_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-28',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Artist', 'Text-to-Image', 'Generation'],
    },
    {
      id: 'zen-artist-edit',
      title: 'Zen-Artist-Edit: Image Editing and Inpainting',
      subtitle: 'Instruction-Following Image Editing',
      abstract: 'Image editing and inpainting capabilities with instruction-following for precise modifications.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-artist-edit_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-artist-edit_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-28',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Artist', 'Image Editing', 'Inpainting'],
    },
    {
      id: 'zen-designer-instruct',
      title: 'Zen-Designer-Instruct: Design Generation',
      subtitle: 'Instruction-Following Design Model',
      abstract: 'Instruction-following design generation model for professional design workflows.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-designer-instruct_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-designer-instruct_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-30',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Designer', 'Instruct', 'Design'],
    },
    {
      id: 'zen-designer-thinking',
      title: 'Zen-Designer-Thinking: Visual Reasoning',
      subtitle: 'Visual Reasoning and Analysis',
      abstract: 'Visual reasoning and analysis for design tasks with chain-of-thought design understanding.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-designer-thinking_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-designer-thinking_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-01-30',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Designer', 'Visual Reasoning', 'Analysis'],
    },
    {
      id: 'zen-scribe',
      title: 'Zen-Scribe: Speech Recognition and Transcription',
      subtitle: 'Multi-Language Speech-to-Text',
      abstract: 'Speech recognition and transcription model with multi-language support and high accuracy.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-scribe_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-scribe_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-01',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Scribe', 'Speech', 'Transcription'],
    },
    {
      id: 'zen-guard',
      title: 'Zen-Guard: Multilingual Safety Moderation',
      subtitle: 'AI Safety and Content Moderation',
      abstract: 'Safety and content moderation across languages for responsible AI deployment.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-guard_whitepaper.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-guard_whitepaper.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-05',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Guard', 'Safety', 'Moderation', 'Multilingual'],
    },
    {
      id: 'zen-reranker',
      title: 'Zen-Reranker: 7680-Dimensional Embeddings',
      subtitle: 'Semantic Optimization with BitDelta Compression',
      abstract: 'High-dimensional embeddings with BitDelta compression for semantic search and retrieval optimization.',
      pdfUrl: 'https://github.com/zenlm/papers/raw/main/pdfs/zen-reranker.pdf',
      latexUrl: 'https://github.com/zenlm/papers/blob/main/zen-reranker.tex',
      githubUrl: 'https://github.com/zenlm/papers',
      date: '2025-02-10',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Reranker', 'Embeddings', '7680-Dim', 'BitDelta'],
    },
    {
      id: 'zen-agent',
      title: 'Zen-Agent: Autonomous AI Agent Model',
      subtitle: 'Planning, Reasoning, and Tool Use',
      abstract: 'Autonomous AI agent model with planning, reasoning, and tool use capabilities.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-agent.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-agent.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Agent', 'Planning', 'Tool Use', 'Autonomous'],
    },
    {
      id: 'zen-3d',
      title: 'Zen-3D: 3D Scene Generation',
      subtitle: 'Text-to-3D and Image-to-3D Synthesis',
      abstract: '3D scene generation from text and image inputs with high-fidelity synthesis.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-3d.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-3d.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', '3D', 'Generation', 'Synthesis'],
    },
    {
      id: 'zen-world',
      title: 'Zen-World: World Model',
      subtitle: 'Predictive World Simulation',
      abstract: 'Predictive world model for simulation and planning in complex environments.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-world.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-world.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'World Model', 'Simulation', 'Prediction'],
    },
    {
      id: 'zen-foley',
      title: 'Zen-Foley: Sound Effects Generation',
      subtitle: 'AI-Powered Foley and Sound Design',
      abstract: 'AI-powered foley and sound effects generation for film, games, and media production.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-foley.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-foley.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Audio', 'Sound Effects', 'Foley'],
    },
    {
      id: 'zen-musician',
      title: 'Zen-Musician: Music Generation',
      subtitle: 'Composition and Arrangement AI',
      abstract: 'AI music generation model for composition, arrangement, and production.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-musician.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-musician.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Music', 'Generation', 'Composition'],
    },
    {
      id: 'zen-voyager',
      title: 'Zen-Voyager: Embodied AI Navigation',
      subtitle: 'Autonomous Exploration and Navigation',
      abstract: 'Embodied AI model for autonomous exploration and navigation in physical and virtual environments.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-voyager.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-voyager.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Embodied AI', 'Navigation', 'Exploration'],
    },
    {
      id: 'zen-technical-paper',
      title: 'Zen Technical Architecture',
      subtitle: 'MoDE Architecture and Training Methodology',
      abstract: 'Technical architecture report covering the MoDE (Mixture of Diverse Experts) design and training methodology.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-technical-paper.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-technical-paper.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Architecture', 'MoDE', 'Technical Report'],
    },
    {
      id: 'zen-reasoning',
      title: 'Zen-Reasoning: Chain-of-Thought Models',
      subtitle: 'Advanced Mathematical and Logical Reasoning',
      abstract: 'Chain-of-thought reasoning model for advanced mathematical and logical problem solving.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-reasoning.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-reasoning.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Reasoning', 'CoT', 'Mathematics', 'Logic'],
    },
    {
      id: 'zen-medical',
      title: 'Zen-Medical: Clinical AI Models',
      subtitle: 'Medical Diagnosis and Clinical Decision Support',
      abstract: 'Clinical AI model for medical diagnosis and clinical decision support systems.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-medical.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-medical.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Medical', 'Clinical', 'Diagnosis', 'Healthcare'],
    },
    {
      id: 'zen-voice-clone',
      title: 'Zen-Voice-Clone: Voice Synthesis',
      subtitle: 'Zero-Shot Voice Cloning and TTS',
      abstract: 'Zero-shot voice cloning and text-to-speech synthesis with high fidelity.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-voice-clone.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-voice-clone.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Voice', 'TTS', 'Cloning', 'Synthesis'],
    },
    {
      id: 'zen-translator',
      title: 'Zen-Translator: Neural Machine Translation',
      subtitle: 'Multilingual Translation Across 100+ Languages',
      abstract: 'Neural machine translation model supporting 100+ languages with high quality.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-translator.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-translator.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Translation', 'NMT', 'Multilingual'],
    },
    {
      id: 'zen-video',
      title: 'Zen-Video: Video Generation',
      subtitle: 'Text-to-Video and Video Editing',
      abstract: 'Text-to-video generation and video editing model with temporal consistency.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-video.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-video.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Video', 'Generation', 'Editing'],
    },
    {
      id: 'zen-director',
      title: 'Zen-Director: AI Film Production',
      subtitle: 'Scene Composition and Cinematography AI',
      abstract: 'AI-powered film production model for scene composition and cinematography.',
      pdfUrl: 'https://github.com/hanzoai/papers/raw/main/pdfs/zen/zen-director.pdf',
      latexUrl: 'https://github.com/hanzoai/papers/blob/main/zen/zen-director.tex',
      githubUrl: 'https://github.com/hanzoai/papers',
      date: '2025-02-20',
      authors: ['Hanzo AI Inc', 'Zoo Labs Foundation'],
      tags: ['Zen', 'Film', 'Director', 'Cinematography'],
    },
  ],
}
